### ISSUE TITLE
Ortho4XP not finding major airports

### ISSUE THREAD

**Issue by speedbird5** [oscarpilote/Ortho4XP#1]
Hi, when I select "Build vector data" for the tile +47-123, containing KPAE -  Snohomish County Airport north of Seattle, USA, the output does not find this airport which is a major airport.

I have checked OSM and it is correctly tagged as "aeroway"="aerodrome",.  In fact, many airports within this tile are missed.

Is there a further filter being applied?

Is there a way of selecting airports of a certain size or type?

It would be great to be able to set these parameters in the cfg file.

These are the ones it found, some of which are minor.

    Recycling OSM data for way["aeroway"="aerodrome"]
     A total of 126 node(s) and 5 way(s).
       * KSEA Seattle-Tacoma International Airport
       *      Kenmore Air Harbor Seaplane Base
       *      Enumclaw Airport
       * KPLU Pierce County Airport-Thun Field
       *      Harvey Field
    Recycling OSM data for rel["aeroway"="aerodrome"]
     A total of 132 node(s) and 3 relation(s).
       *      First Air Field
       * KBFI Boeing Field
       *      Auburn Municipal Airport

Thanks for the awesome tool !!!!

**Comment by d41k4n** [comment]
KPAE is not tagged sufficiently for Ortho4XP to pick it up. See:

http://forums.x-plane.org/index.php?/forums/topic/114874-how-to-encode-a-boundary-as-a-closed-way-in-osm/

http://forums.x-plane.org/index.php?/forums/topic/116021-flat-airports/

**Comment by speedbird5** [comment]
OK Thanks for the explanation...
