### ISSUE TITLE
using usgs elevation

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#105]
I just set custom_dem to NED 1/3" (from usgs) - USA. 
Things appear to go along and noting stops a process, but I am seeing the following error message in the ortho4 window:
WARNING: unsupported raster (install Gdal): ./Elevation_data/+20-100/N29W092_NED13.img -> replaced with zero altitude.

I do have Gdal installed and homebrew reports it as being up to date.

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/139847-v130-bugs/&do=findComment&comment=1398580

**Comment by OldSubSailor** [comment]
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gdal'
>>>

**Comment by d41k4n** [comment]
You haven't installed the required gdal Python module. Please make sure you follow the install instructions.

**Comment by OldSubSailor** [comment]
Was it not installed using the ruby home-brew thing? I did that.  And I see goal listed in my directories.

E.g.
usr/local/bin/gdal_fillnodata.py
/usr/local/bin/gdal_grid
/usr/local/bin/gdal_merge.py
/usr/local/bin/gdal_pansharpen.py
/usr/local/bin/gdal_polygonize.py
/usr/local/bin/gdal_proximity.py
/usr/local/bin/gdal_rasterize

**Comment by OldSubSailor** [comment]
Warning: gdal 2.4.2_3 is already installed and up-to-date

**Comment by OldSubSailor** [comment]
Also there is this little message:
Pouring gdal-2.4.2_3.catalina.bottle.tar.gz
Warning: gdal dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/gdal/2.4.2_3: 280 files, 54.7MB

**Comment by OldSubSailor** [comment]
This concern is not fixed, nor is it properly addressed. In fact, throwing only a link without any sort of helpful response is just plain rude. 
so why is it closed?

**Comment by d41k4n** [comment]
You are missing the gdal Python bindings module (use "pip3 install gdal" or "pip install gdal"). If that doesn't work it's not Ortho4XP's fault. 

Maybe try this:
https://github.com/SkyTruth/CrowdProjects-frackfinder/wiki/Installing-GDAL-on-OSX-with-pip-install-gdal

It seems this step is missing in the Mac install instructions. If that solves your issue a separate issue should be raised to correct the instructions.

**Comment by OldSubSailor** [comment]
Ah, thank you.  I have posted on the x plane forums regarding the results of the pip3 install attempt.  I get a screen full of red text errors and messages.  I think that that ruby command line ends up installing Gdal as part of the initial home-brew process, because it was already on my drive and I did not install it as a separate step. 
For some reason, things are not communicating, and I sure as heck do not know how to troubleshoot it. 

You say that the Gdal Python binding module is missing.  Can you tell what some of the files in that would be?  
I can find these:
/usr/local/Cellar/gdal/2.4.2_3/lib/python3.7/site-packages/gdal.py
/usr/local/Cellar/gdal/2.4.2_3/lib/python3.7/site-packages/osgeo/gdal.py
/usr/local/lib/python3.7/site-packages/gdal.py
/usr/local/lib/python3.7/site-packages/osgeo/gdal.py
which appear to buried in or with python3.7.

**Comment by OldSubSailor** [comment]
Also, ortho does appear to download the USGS file, but evidently Gdal fails to follow through.
