### ISSUE TITLE
Issues with Mac install

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#106]
Internet searches show that there remain issues with Gdal, python and perhaps Macs.
I tried to give you a detailed report as best as I could. You blew it off and ended up saying that I did not install it correctly without even asking any probative questions. 
You also sent me a link to a forum page that was full of text and pictures.  Why did you not just copy and paste the relevant information rather than the link? 
You said that ortho4 fully supports python 3.8, however it looks like part of it relies on things that remain in or associated with python 3.7 
 % gdal_auth.py      
Traceback (most recent call last):
  File "/usr/local/bin/gdal_auth.py", line 37, in <module>
    from osgeo import gdal
ImportError: No module named osgeo
:
/usr/local/Cellar/gdal/2.4.2_3/lib/python3.7/site-packages/osgeo

**Comment by d41k4n** [comment]
Why would you want to execute gdal_auth.py? It's nothing Ortho4XP would ever need.
You are still lacking Python gdal bindings, as mentioned multiple times.
This is no issue for which Ortho4XP is directly responsible and therefore I think it doesn't belong here but instead should be discussed in the [official support forum](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/).
Furthermore, you did not provide any feedback as to whether or not you followed instructions as per the link I provided in my [other comment](https://github.com/oscarpilote/Ortho4XP/issues/105#issuecomment-572692059) . Depending on that result I would have raised an issue for improving the install docs (since I'm not on a Mac I can't test that myself).

I'll paraphrase the relevant linked instructions here for your convenience (you might have to adjust paths depending on the gdal version):

1. First create GDAL system files by running pip3 install gdal (thus generating errors). The next steps merely involve targeting the resulting errors.

2. Next, set CPATH in your environment. The compiler needs to know where to find GDAL headers:
```
export CPATH=/Library/Frameworks/GDAL.framework/Headers
```
3. Verify that your installation of GDAL lives in /Library/Frameworks on your system. I recommend adding the CPATH command to your .bashrc

4. Set symbolic links to put things where the GDAL compile script assumes they will be: 
```
cd /Library/Frameworks/GDAL.Framework/Versions/2.1
ln -s ../../unix/lib lib
ln -s Libraries libs
```

**Comment by OldSubSailor** [comment]
I do apologize, I had been at this for almost all day and hit a frustration plateau. 

I take it that by the instructions in your other comment, you mean “import Gdal”,  alas, I sort of got lost in all the text and pictures.  
I thought that I had reported the result in various places.  
So I have done my best to completely delete python3.7 and python 3.8 from my iMac, and will be reinstalling everything soon.

I do believe that the install instructions for maxOS left out the install python 3.x  prior to running the ruby script to install home-brew. 
I also have seen that install_mac.sh file has the step to install the Gdal "brew install python gdal spatialindex p7zip”, so I guess this is where the Gdal that I found on my iMac came from.  I did run that scrip on my previous install. 

I  will follow up on more feed back when I finally get things reinstalled.
Thank you

**Comment by OldSubSailor** [comment]
I was just looking for/at Gdal when I executed it to see how it worked. 

I have everything reinstalled, with ortho working as before. 

With regard to the first comment,
% python3
Python 3.7.6 (v3.7.6:43364a7ae0, Dec 18 2019, 14:18:50) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gdal'
>>> ^D

I saw this when I ran the shell script (along with pages of other things)

 Pouring gdal-2.4.2_3.catalina.bottle.tar.gz
Warning: gdal dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/gdal/2.4.2_3: 280 files, 54.7MB
==> Downloading https://homebrew.bintray.com/bottles/spatialindex-1.9.3.catalina.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/fb/fbcbfaf6510137f3168a0dc57cbac8c8b1435094b1ede9d35a30fa6ccaea28f4?__gda__=exp=1576450614~hmac=0124215dc313c6f276e46b1fde2eb8c271d14034c986b3d0ac47e1db3717557b&response-c

So I would have thought that the Gdal things were installed then?  I guess that it is  not the same thing as pip3 install you mentioned.

**Comment by OldSubSailor** [comment]
The shell for macOS is now the zsh  so I guess that would be 
I can not find any Gdal in /Library/Frameworks.
The pip3 install continues to generate a page load of error messages etc.  Of course I have no idea as to what “

I am just trying to show you what I do and don’t see. 
> The next steps merely involve targeting the resulting errors.
> 
“ means.  So does all this mean that the sh script in the install instructions may be in error?

**Comment by OldSubSailor** [comment]
I don’t know what directions things are going.
Would you know if this is ortho or python  or Mac errors

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "./src/O4_Parallel_Utils.py", line 18, in run
    self._success[0]= self._task(*args) and self._success[0] 
  File "./src/O4_Mask_Utils.py", line 311, in build_mask
    blur_width=[L/pxscal for L in tile.masks_width]
TypeError: 'int' object is not iterable

Evidently, it prevents parts of scenery being included in the ortho tile folder

**Comment by d41k4n** [comment]
This is going all over the place - not very helpful with getting true issues with Ortho4XP fixed...

I've changed the title to something a bit more appropriate.

I guess we can ignore your last comment as you figured it out yourself already (masking_mode related).

Regarding:

> The shell for macOS is now the zsh so I guess that would be I can not find any Gdal in /Library/Frameworks.

I suggest you do some searching on the web. There are plenty of places where you can get help on the topic of installing GDAL + Python bindings for Mac.

And just to repeat: Since I don't have a Mac I can't answer all your questions nor can I test the validity of any instructions. Also, I'm not the original author of Ortho4XP, so don't blame me for things I wasn't responsible for.

**Comment by OldSubSailor** [comment]
I’m sorry and in no way blame you. I wish that we could find you some Mac heavy kind of guys to help you out. 
FYI, I and others appear to be having issues in trying to install the GDAL bindings, and I am attempting to use the forums to work it out. 
On issue for me is, that I don’t know enough to know if it is an Ortho4XP issue or a python issue or a macOS issue.

**Comment by d41k4n** [comment]
Please let me know if you find a solution that works for you. It would be great if we could improve the installation procedure and instructions via a pull request.

In the meantime maybe have a look at some related search results:
https://www.google.com/searchq=gdal+python+bindings+mac+osx

**Comment by OldSubSailor** [comment]
I will do. 

Alas I just got

404. That’s an error.

The requested URL /searchq=gdal+python+bindings+mac+osx was not found on this server.  That’s all we know.

**Comment by d41k4n** [comment]
You were too fast - I had to correct a copy&paste error - try again :)

**Comment by OldSubSailor** [comment]
Bit lost here, where is the corrected copy and paste?  I went back to the previous email and got that 404 again.

**Comment by d41k4n** [comment]
Don't use your email, use the Github website.

**Comment by OldSubSailor** [comment]
OOPs, got it.

**Comment by OldSubSailor** [comment]
I am seeking more knowledge so that in turn I/we can help you. 
By way of explanation.
With regard to Gdal.
I saw something regarding Gdal flash by on my terminal screen when I ran the install sh script.
I searched my iMac using the locate gdal command and got a large listing of the nature of:
/usr/local/Cellar/gdal/2.4.2_3
.
.
.
/usr/local/bin/gdal-config
I hope that this in a way explains my confusion regarding your telling me that I did not have Gdal installed, coupled with that no module installed error message. 
To me, it was as if Gdal was there, but nothing nor no one could access it.  
That is why I tried that "execute gdal_auth.py" just to see if anything was responding.

Now I will continue to use that link and see if I can find anything that I can do.

**Comment by d41k4n** [comment]
I never said you did not have GDAL installed. I always referred to the GDAL **Python bindings** - which is something different (albeit related).

**Comment by OldSubSailor** [comment]
My error. I am still searching the internet with the link you provided.

**Comment by OldSubSailor** [comment]
Good morning,

A user is reporting this error:

ModuleNotFoundError: No module named ‘pyproj.crs'

I am trying to help him.  Can you tell me what step in the process installs this module?
Thank you,
trav

A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by OldSubSailor** [comment]
% python3 Ortho4XP_v130.py 
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 14, in <module>
    import O4_Geo_Utils as GEO
  File "./src/O4_Geo_Utils.py", line 2, in <module>
    import pyproj
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/__init__.py", line 81, in <module>
    from pyproj.crs import CRS  # noqa: F401
ModuleNotFoundError: No module named 'pyproj.crs'

**Comment by OldSubSailor** [comment]
It looks like the pyproj was installed but I am not sure:

Building wheels for collected packages: pyproj
  Building wheel for pyproj (PEP 517) ... done
  Created wheel for pyproj: filename=pyproj-2.4.2.post1-cp38-cp38-macosx_10_9_x86_64.whl size=385567 sha256=eeec09d7d31b88693003831cb3950bb675b5c95ec80822371aed705ac2ad7d58
  Stored in directory: /private/var/folders/81/dknbj9t122v60nzlhfx5sspc0000gn/T/pip-ephem-wheel-cache-96kl54dd/wheels/cd/4d/b5/3ee84377669dbd035549164debd46ef4b88baabb8c99f8900e
Successfully built pyproj

**Comment by OldSubSailor** [comment]
I don't know where pyproj.crs is or how to get it.

But what do I know? % pip3 install pyproj.crs 
ERROR: Could not find a version that satisfies the requirement pyproj.crs (from versions: none)
ERROR: No matching distribution found for pyproj.crs
But what do I know? % locate pyproj.crs
But what do I know?

**Comment by OldSubSailor** [comment]
But what do I know? % brew info pyproj.crs
Error: No available formula with the name "pyproj.crs" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
But what do I know? %

**Comment by OldSubSailor** [comment]
evidently the installer script step:
pip3 install git+https://github.com/jswhit/pyproj.git
is now returning a non-usable pyproj.
We are now having to enter
pip3 install prproj==1.9.6
i have gotten 2.4.2 and 2.4.1 to work also.

**Comment by OldSubSailor** [comment]
Consider changing the install sh script to include the Ruby step.
#Install Homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install dependencies
brew install python gdal spatialindex p7zip

# Install pyproj
pip3 install cython
pip3 install git+https://github.com/jswhit/pyproj.git

# Install other dependencies
pip3 install numpy shapely rtree pillow requests
