### ISSUE TITLE
apt_smoothing_pix sinks runway into ground

### ISSUE THREAD

**Issue by barf** [oscarpilote/Ortho4XP#110]
just wondering if I'm doing something wrong.. setting this value to either 8 or 0 makes no apparent difference to the runway surface in my DEM, the resulting runway is always sunk into the ground. 

Sometimes significantly sunk into the ground, as in this example: 
![NH90 - 2020-01-24 06 22 49](https://user-images.githubusercontent.com/584684/73007957-5d41ab00-3e72-11ea-9ee1-437356baec8f.png)
Does Ortho4XP take the airfield elevation from somewhere and flatten the DEM to that value? Any help would be appreciated!

PS. Real runways, AFAIK, are always elevated slightly from the surrounding terrain for drainage, so I was surprised to see runways sunk into the ground... it could be a problem if water pooling and hydroplaning was simulated in XP! ;-)

**Comment by GoldJohnKing** [comment]
If the airport enabled runway follow terrain feature, elevation included in orthos wont apply to the airport.

By the way, what actually does the param do exactly? I didn't really understand what the hint means.

2020年1月23日 18:28，foo barf <notifications@github.com>写道：

just wondering if I'm doing something wrong.. setting this value to either 8 or 0 makes no apparent difference to the runway surface in my DEM, and the resulting runway is always slightly sunk into the ground. Sometimes significantly sunk into the ground (does it take the airfield elevation from somewhere and flatten to that value?)

Real runways, AFAIK, are always elevated slightly from the surrounding terrain for drainage, so I was surprised to see runways sunk into the ground by Ortho4XP... it could be a problem if water pooling and hydroplaning was simulated in XP! ;-)

**Comment by barf** [comment]
The airport and XP setting is to follow terrain, I have that figured out. What I'm trying to do is introduce runway contours from LiDAR but the setting here seems to flatten it too much and can't be disabled.

Reading the code, if I understand correctly (no guarantees!!) it applies a Gaussian blur to Z (height) values around the area of the runway and taxiways. But if possible I'd prefer to do this myself in QGIS or by manipulating a TIN in blender.

**Comment by barf** [comment]
closing. solved with QGIS but a feature request might come from this yet
