### ISSUE TITLE
No OSM Preview on Mac OS X (High Sierra)

### ISSUE THREAD

**Issue by ssharpe83713** [oscarpilote/Ortho4XP#111]
1.30 works great on my Mac; however, I don't get an OSM Preview map at any zoom level.  The black frame is there, but inside remains white.  The other Previews are fine.  Any clue?  It would be nice to have OSM to more quickly locate my target airports!

**Comment by d41k4n** [comment]
Could be a temporary issue with the OSM tile servers. Did you try purging the content of the Previews folder?

**Comment by ssharpe83713** [comment]
Thanks for the quick response, Oscar.  I replaced the OSM.lay file with the
current version, and that fixed it!

Steve

**Comment by ssharpe83713** [comment]
Oscar,

I built a Windows 10 pc for X-Plane and downloaded Ortho4XP 130 to it.  I
launched the binary executable, no problem, but it doesn't show the OSM
Preview at any zoom level (other previews fine).  I updated the OSM.lay
file to match the current Github version...still no OSM Preview???

Steve

**Comment by d41k4n** [comment]
Did you try purging the content of the Previews folder?

**Comment by ssharpe83713** [comment]
That worked.  Thanks for the quick response, Oscar!
