### ISSUE TITLE
DSFTool.exe stop work

### ISSUE THREAD

**Issue by lanceji** [oscarpilote/Ortho4XP#112]
when i extract overylays use  \zzz_hd_global_scenery4\Earth nav data\+30+130\+34+135.dsf 
then DSFTool.exe stop work.

Is the file too large?
+34+135.dsf    : https://drive.google.com/open?id=1is25QDNEK3IY6qnoCEOBtBbiUVrExEjQ

![1](https://user-images.githubusercontent.com/6231234/74268087-3cb69380-4d42-11ea-94e4-5204d7e78679.png)

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/136386-error-when-building-overlay/&tab=comments#comment-1308029
