### ISSUE TITLE
Arch Linux install

### ISSUE THREAD

**Issue by Stevo2444** [oscarpilote/Ortho4XP#113]
Hello, I've installed Ortho4XP several times successfully on debian/ubuntu-based distributions but on each attempt on an Arch-based distribution I cannot install all of the required packages. Google turns up nothing to assist and the Arch-wiki doesn't deal with these packages. In particular, the following packages are not found:
python3-pil.imagetk
p7zip-full
libnvtt-bin
freeglut3
I've tried installing with both pacman and python's pip.
Can anyone give me any advice on how to get Ortho4XP running on Arch?
Thanks,
Steve

**Comment by d41k4n** [comment]
Here's an (older) comment on the [official support forum](https://forums.x-plane.org/index.php?/forums/topic/90469-ortho4xp) from a user that apparently is/was using 1.2 successfully on Arch Linux:
https://forums.x-plane.org/index.php?/forums/topic/90469-ortho4xp/&do=findComment&comment=964202

Maybe try getting in touch and share any useful insights you might get in the process.

Hint: The support forum is likely the much better place to discuss issues like these anyway.

**Comment by Stevo2444** [comment]
Point taken and thanks for the link. I'll do some reading and see what I can come up with. 
Cheers!

**Comment by Stevo2444** [comment]
OK, that link helped but I still needed to decipher what was going on. I've done one successful test on Arcolinux (Arch) using the steps below. I've set it out so that when someone else can test they work, perhaps it can go in as an amendment to the installation text file? I'll also post to the official support forum so others can test it.

The only thing I didn't do was use yay to install nvidia-texture-tools. I downloaded the package from git (as per the link in the post above) and built and installed the package manually. I think yay would do all of this in one command?


[proposed to insert after debian instructions]
For Arch-based distributions, some names are slightly different and there is an extra step involving the AUR as follows:

Step 1: (you must have the AUR enabled) then in the command line

yay nvidia-texture-tools

(this will download, build and install the Nvidia Texture Tools package which includes some necessary modules for Ortho4XP)
 
Step 2: in the command line

sudo pacman -S python python-pip python-requests python-numpy python-pyproj python-gdal python-shapely python-rtree python-pillow python-pmw freeglut

To execute the program, CD to the Orth4XP directory in the command line and type

python Ortho4XP_130.py

**Comment by d41k4n** [comment]
Thanks for the feedback. 

Unfortunately I can't comment on any of that as I don't use Arch. 

> I'll also post to the official support forum so others can test it.

Would be great if you could post a link to your forum post once it's up.

> Perhaps once the steps are confirmed, the text below can be put into the install instructions?

Of course any additions/corrections to the current [install_instructions.txt](https://github.com/oscarpilote/Ortho4XP/blob/master/Install_Instructions.txt) are welcome. Feel free to submit a pull request as needed.

**Comment by Stevo2444** [comment]
Thank you. I'll do a pull request when I get some further testing feedback and when I learn how to do a pull request

**Comment by Stevo2444** [comment]
Pull request done, I think. First time so hope it's correct.
