### ISSUE TITLE
Probably uncatched OSM error when building mesh at +23+120

### ISSUE THREAD

**Issue by GoldJohnKing** [oscarpilote/Ortho4XP#116]
I'm really new to this... I've never encounter similar issue when bulding other areas, and I'm pretty sure it's not a memory issue. Would you please enlighten me?

Full logs below:
```
Step 2 : Building mesh for tile +23+120 : 
--------

-> Modifying curv_tol weight map according to runway locations.
-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from ./OSM_data/+20+120/+23+120/+23+120_coastline.osm.bz2
      A total of 2662 new node(s), 68 new ways and 0 new relation(s).
-> Start of the mesh algorithm Triangle4XP.
   Mesh command: ./Utils/Triangle4XP -pAuYBVP 102470.132 111319.491 3673 3673 -0.01 -0.01 1.01 1.01 -32768 0.948812467 10 15.456831011317595 ./Tiles/zOrtho4XP_+23+120/Data+23+120.alt ./Tiles/zOrtho4XP_+23+120/Data+23+120.weight ./Tiles/zOrtho4XP_+23+120/Data+23+120.poly
   Loading altitudes from DEM file.
   Loading curv_tol geographic weights.
   Computing curvatures from altitudes.
   Opening ./Tiles/zOrtho4XP_+23+120/Data+23+120.poly.
   Opening ./Tiles/zOrtho4XP_+23+120/Data+23+120.node.
   Constructing Delaunay triangulation by divide-and-conquer method.
   Sorting vertices.
   Forming triangulation.
   Removing ghost triangles.
   Recovering segments in Delaunay triangulation.
   Constructing mapping from vertices to triangles.
   Recovering PSLG segments.

WARNING: Triangle4XP could not achieve the requested quality (min_angle), most probably due to an uncatched OSM error.
It will be tempted now with no angle constraint (i.e. min_angle=0).
   Loading altitudes from DEM file.
   Loading curv_tol geographic weights.
   Computing curvatures from altitudes.
   Opening ./Tiles/zOrtho4XP_+23+120/Data+23+120.poly.
   Opening ./Tiles/zOrtho4XP_+23+120/Data+23+120.node.
   Constructing Delaunay triangulation by divide-and-conquer method.
   Sorting vertices.
   Forming triangulation.
   Removing ghost triangles.
   Recovering segments in Delaunay triangulation.
   Constructing mapping from vertices to triangles.
   Recovering PSLG segments.

ERROR: Triangle4XP really couldn't make it !

If the reason is not due to the limited amount of RAM please
file a bug including the .node and .poly files that you
will find in ./Tiles/zOrtho4XP_+23+120.
```

Required files here (larger than 10MB and could not upload via github):
https://mega.nz/#!Lm4SBSJQ!otgG7WKnjrv1Mza3n1JF0zP0UOPDiwStJmYyWcBKMC4

**Comment by d41k4n** [comment]
Try reducing your road_level < 4 and delete cached OSM data for the tile and redo steps 1 + 2.

Maybe also check out similar topics in the Ortho4XP support forum:
https://www.google.com/search?q=ortho4xp+"Triangle4XP+really+couldn't+make+it"+site%3Aforums.x-plane.org

If you require further troubleshooting or have further questions I suggest you post in the [forum](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/).

**Comment by GoldJohnKing** [comment]
I've deleted the cached files multiple times and I'm pretty sure it's not caused by download corruption.

Reduce road_level to 3 or reduce max_levelled_segs to 250000 would help.

The most difference between my issue and the online posted issue is, theirs would output infos like `Splitting subsegment (0.978614661357, 0.57065705109) (0.978737929608, 0.570659482065) at (0.978737929608, 0.570659482065).` but mine only have `Recovering PSLG segments.` above the error line, even though I set verbose to 3, so I doubt if it's a diffenent issue or bug.

**Comment by d41k4n** [comment]
I could not reproduce your issue on my end using road_level=3 and max_levelled_segs=100000.

**Comment by d41k4n** [comment]
Note that I've never said it's caused by download corruption. Purging the OSM cache has other benefits, especially if you're changing the road_level parameter between 2-5 (as per the hint text for "road_level").

**Comment by GoldJohnKing** [comment]
> Note that I've never said it's caused by download corruption. Purging the OSM cache has other benefits, especially if you're changing the road_level parameter between 2-5 (as per the hint text for "road_level").

Yes, everytime I rebuild this block, I clean all data of it. It always happens.

> I could not reproduce your issue on my end using road_level=3 and max_levelled_segs=100000.

Yes.
As I said, reduce road_level to 3 or set max_levelled_segs lower than 250000 would not reproduce the issue.

**Comment by jujunet37** [comment]
Hi,
Hi have same issue when trying to build +48-003 tile. I tried many parameters, such as road_level to 0, 1 (default), 3. Max_levelled_segs to 100000 (default) or 250000, delete OSM cache... no luck.
Some ideas ?

**Comment by GoldJohnKing** [comment]
> Hi,
> Hi have same issue when trying to build +48-003 tile. I tried many parameters, such as road_level to 0, 1 (default), 3. Max_levelled_segs to 100000 (default) or 250000, delete OSM cache... no luck.
> Some ideas ?

Nope... If you set road_level to 0, it means no road data would be used, so it may not related to roads. May be the original data provided by OSM was just incorrect. If you know how to read OSM data, you can try to locate the issue in OSM data.

**Comment by jujunet37** [comment]
Hi. I have no idea how to read OSM data, even when I can read it I will understand, nothing ! :-D
That's stange, I already generated 1/4 west France, and this tile, won't be encoded. What kind of problem can happen in OSM data to produce an error?

**Comment by GoldJohnKing** [comment]
> Hi. I have no idea how to read OSM data, even when I can read it I will understand, nothing ! :-D
> That's stange, I already generated 1/4 west France, and this tile, won't be encoded. What kind of problem can happen in OSM data to produce an error?

I've build all china and only one block has the issue...

OSM fault, for example, could be roads across coastlines. 
You could see this: https://github.com/oscarpilote/Ortho4XP/issues/66 The roads used to be across the coastline and in the river.

**Comment by d41k4n** [comment]
@jujunet37: Your issue is likely due to a section of the english channel being tagged with "natural=water":

https://www.openstreetmap.org/relation/9280887
 
IMO that upsets the triangulation due to the fact that Ortho4XP will have overlapping/identical segments as inland water and coastline.... The workaround is to delete that relation including all its members from "./OSM_data/+40-010/+48-003/+48-003_water.osm.bz2" and re-run steps 1 + 2. At least it did the trick for me so that the triangulation step completed successfully.

FYI: There exist a multitude of tools that can check OSM data for consistency and errors:
https://wiki.openstreetmap.org/wiki/Quality_assurance#Error_detection_tools

Usually, Ortho4XP is pretty good at cleaning/rejecting bad road, inland water and coastline geometry on its own but that doesn't mean it works in all cases.

Last but not least, I think issues like these would get a lot more exposure/feedback by discussing them in the official [Ortho4XP support forum](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/).

**Comment by GoldJohnKing** [comment]
So it's caused by provided OSM data instead of Otrho4XP itself for sure. I would close the issue.

**Comment by jujunet37** [comment]
Thank you for help, I see more clearly now. But unfortunately I can't figure out this issue, it appear that the crash location, is in the sea, at a place where there is nothing. I will post in Xplane forums, to go further.
