### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#117]
I am seeing this and do not know where it is coming from. 

   * Downloading OSM data for ('node["aeroway"]', 'way["aeroway"]', 'rel["aeroway"]')
   KTCS   Truth or Consequences Municipal Airport                      5 runways, lat= 33.24, lon= -107.27
   ****   Adobe Ranch Private Airport                                  1 runway , lat= 33.58, lon= -107.90
   ****   Chloride Airport                                             1 runway , lat= 33.33, lon= -107.66
   ****   ****                                                         2 runways, lat= 33.58, lon= -107.25
   ****   ****                                                         1 runway , lat= 33.04, lon= -107.04
   Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+30-110/N33W108_NED13.img from USGS.
    * Min altitude: 1274.6971 , Max altitude: 3285.279 , Mean: 1973.4884

**list index out of range
list index out of range
list index out of range
list index out of range
list index out of range
list index out of range**

  Auto-patched 10 runways and 6 pieces of taxiway.
   Flattened 4 helipads.
   Number of edges at this point: 3901

![Screen Shot 2020-03-06 at 10 23 47 PM](https://user-images.githubusercontent.com/54075170/76136696-1fe84580-5ffa-11ea-9c78-a8f2a6bc8188.jpg)

**Comment by d41k4n** [comment]
Are you able to continue with tile creation and does the scenery look okay in X-Plane?

If so, I'd say you can ignore these messages.

Otherwise please increase verbosity to max, re-run step 1 and attach the output messages as well as the .cfg file(s).

**Comment by OldSubSailor** [comment]
I apologize for taking so long. This was one of those intermittent things. 
No, it did not appear to impact tile creation
I have not seen if for a while now.
