### ISSUE TITLE
All kinds of config files and permissions issues!

### ISSUE THREAD

**Issue by juanjolozadap** [oscarpilote/Ortho4XP#119]
![image](https://user-images.githubusercontent.com/58301362/79172901-6afd3180-7dcc-11ea-9e8f-2b9ab98f31cb.png)

Really, I used to be able to generate tiles months ago before I took a break from simming. But then I come back, follow the exact same steps as before, but I'm getting all kinds of "unable to write" or "check permissions", or "no config files for tile X" ERRORS.

Frustrating is the least to say.

Then we have MSFS around the corner, and it has me wondering why wouldn't I wait for it to come out with their presumably AIO solutions to flight-sim experience.

I tried changing permissions to folders, to entire drives, but nothing seems to make it work. I'm utterly stuck.

If I can get this sorted out then that would be great. Cheers

**Comment by d41k4n** [comment]
Does the error happen if you select a different base folder on a different local drive?
