### ISSUE TITLE
+48-3 has a mesh issue

### ISSUE THREAD

**Issue by sailando** [oscarpilote/Ortho4XP#122]
Using 1.30 on Windows 10. getting this. 200 other tiles worked fine.
.node and .poly attached in zip file.

[zOrtho4XP_+48-003.zip](https://github.com/oscarpilote/Ortho4XP/files/4496921/zOrtho4XP_%2B48-003.zip)

Step 2 : Building mesh for tile +48-003 : 
--------

-> Modifying curv_tol weight map according to runway locations.
-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from ..\OSM_data\+40-010\+48-003\+48-003_coastline.osm.bz2
-> Start of the mesh algorithm Triangle4XP.
   Loading altitudes from DEM file.

   Loading curv_tol geographic weights.

   Computing curvatures from altitudes.

   Constructing Delaunay triangulation by divide-and-conquer method.

   Recovering segments in Delaunay triangulation.

   Internal error in segmentintersection():

   Topological inconsistency after splitting a segment.

   Splitting subsegment (0.7803597, 0.5709207) (0.780358137985, 0.571076022852) at (0.780358137985, 0.571076022852).

WARNING: Triangle4XP could not achieve the requested quality (min_angle), most probably due to an uncatched OSM error.
It will be tempted now with no angle constraint (i.e. min_angle=0).
   Loading altitudes from DEM file.

   Loading curv_tol geographic weights.

   Computing curvatures from altitudes.

   Constructing Delaunay triangulation by divide-and-conquer method.

   Recovering segments in Delaunay triangulation.

   Internal error in segmentintersection():

   Topological inconsistency after splitting a segment.

   Splitting subsegment (0.7803597, 0.5709207) (0.780358137985, 0.571076022852) at (0.780358137985, 0.571076022852).

ERROR: Triangle4XP really couldn't make it !

If the reason is not due to the limited amount of RAM please
file a bug including the .node and .poly files that you
will find in ..\Tiles\zOrtho4XP_+48-003.

**Comment by d41k4n** [comment]
This is a topological inconsistency in the OSM data, not a bug.

Please see:
https://forums.x-plane.org/index.php?/forums/topic/204708-osm-error-at-48-003/
