### ISSUE TITLE
Future Warning

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#126]
My terminal screen **fills** with these two lines when I launch Ortho4XP. I don't know at what steps or files cause this, and tried contacting the pyproj folks.  They recommend that I move the concern here. At this time this appears to have no negative impact in running Ortho4XP, but will it in some future?  Would it hurt to be proactive?  If I knew what to do or how to help I would be glad to. 

\/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))

**Comment by snowman2** [comment]
Looks like on of the places in the code causing the issues is:
https://github.com/oscarpilote/Ortho4XP/blob/3c456b957a20564ad93e105c60f6c33bbc72a310/src/O4_Geo_Utils.py#L18-L30

I cannot see that the code is used anywhere, so it might be able to be removed.
If not, see: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1

**Comment by OldSubSailor** [comment]
Thank you
A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

**Comment by 0ceanic** [comment]
I will look into this.

PyProj is transitioning to different transformation classes. It won't go away any time soon, but I will enter a PR to migrate over to the pyproj 2 approach

**Comment by 0ceanic** [comment]
Ok I have addressed the issue - however I am not sure how active Oscar in approving PR recently.
