### ISSUE TITLE
install_mac.sh and Install instructions 

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#131]
What is it that Mac users need the Homebrew master install for? It sure installs a lot of stuff.  How much is actually necessary?
Why is brew installing Python 3.7 when we go to Pyton.org and install Python 3.8.3 and Python 3.9 on the way?

**Comment by OldSubSailor** [comment]
Also from my latest testing around, the step to brew install python is not necessary if the latest version of python has been installed from python.org. Using this step installs version 3.7, which can lead to having 3 versions of python on the Mac and can even "confuse" the pip3 install process.  That being said, the python recommended install is now:

python3 -m pip install _PACKAGE X_

**Comment by 0ceanic** [comment]
> What is it that Mac users need the Homebrew master install for? It sure installs a lot of stuff. How much is actually necessary?
> Why is brew installing Python 3.7 when we go to Pyton.org and install Python 3.8.3 and Python 3.9 on the way?

Ortho4XP depends on several other packages/binaries. Homebrew installs all those binary dependencies so you don't have to compile them from source (such as GDAL etc.). Every single package that Homebrew installs is needed.

In addition we use Homebrew to install Python3. Mac OS comes with python 2.7 preinstalled which is no good.
To your question about the python version, you shouldn't be downloading python from python.org. Homebrew does that for you with added benefit of managing and maintaining the python installation so avoid having several different python installations.

> Also from my latest testing around, the step to brew install python is not necessary if the latest version of python has been installed from python.org. Using this step installs version 3.7, which can lead to having 3 versions of python on the Mac and can even "confuse" the pip3 install process. That being said, the python recommended install is now:
> 
> python3 -m pip install _PACKAGE X_

With respect to your point about the python version, Homebrew is currently installing 3.7.7 (although there is a 3.8.3 version available on Homebrew). The fact that we are installing a some what older version is not necessarily bad, in fact it make sit more likely all our dependencies work great together. In programming, the "latest" version is not always the best way around it. I recommend you stick with 3.7.3 for now.

Finally what you refer to as the "python recommended install" is actually what we also use in the script to install all python dependencies. 
'python3 -m pip install PACKAGE X' is equal to 'pip3 install PACKAGE X'

**Comment by OldSubSailor** [comment]
Howdy,
The comment regarding. " Python3 -m pip install ... " is based on this response from the folks at
python - Pillow

Is the python3 -m pip install X the fix to all this?
Yes, in the future, if you see instructions like one of these:

pip install X
pip3 install X
It's generally better to do:

python3 -m pip install X
That way you know you're installing X for the same exact same Python you get when you run python3

**Comment by OldSubSailor** [comment]
With regard to installing Python the install instructions may have confused a few folks.
Under the Windows step 1 it reads:
 "1) Download and install Python 3 from www.python.org "

And under the Mac install .sh it reads
# Install dependencies
brew install python ...

I am not sure, but I thinking that the the Windows statement has had us thinking that we should install the latest version.
And I have seen the comments to always install the latest version when looking around the internet

Also, in reading the X-plane forum, I have seen a lot of resistance from people with regard to running that install shell script (or perhaps they do not know how to run it), so the installation process is copy and paste each instruction.  In this case, it becomes more of what we have started to call "The Reading Test" .  Which is indeed frequently failed.

**Comment by OldSubSailor** [comment]
As of Big Sur, DO NOT DOWNLOAD Python from Homebrew.

**Comment by OldSubSailor** [comment]
11/22/2020
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
