### ISSUE TITLE
Step 4 Overlay Error messages

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#132]
> I and another user are seeing this now:
> Step 4 : Extracting overlay for tile +50-121 : 
> --------
> 
> -> Making a copy of the original overlay DSF in tmp dir
> -> The original DSF is a 7z archive, uncompressing...
> -> Converting the copy to text format
>      Converting ./tmp/+50-121.dsf from DSF to text as ./tmp/+50-121_tmp_dsf.txt
>      File ./tmp/+50-121.dsf had 0 ter, 0 obj, 0 pol, 0 net.
>      Converted ./tmp/+50-121.dsf to ./tmp/+50-121_tmp_dsf.txt
> -> Selecting overlays for copy/paste
> -> Converting back the text DSF to binary format
>      Converting ./tmp/+50-121_tmp_dsf_without_mesh.txt from text to DSF as ./tmp/+50-121_tmp_dsf_without_mesh.dsf
>      Scanning for dimension properties...
>      ERROR: the DSF boundaries are out of range.  This can indicate a missing or corrupt sim/dimension properties.
>      ERROR: Error convertiong ./tmp/+50-121_tmp_dsf_without_mesh.txt to ./tmp/+50-121_tmp_dsf_without_mesh.dsf
> -> Coping the final overlay DSF in ./yOrtho4XP_Overlays/Earth nav data/+50-130

============================================================
A tile folder is created in the Overlays folder but that folder is  empty.

I did not know if it has anything to do with P7zip:
brew info p7zip
p7zip: stable 16.02 (bottled)

**Comment by d41k4n** [comment]
That particular error was discussed countless times in the Ortho4XP support forum:
https://www.google.com/search?q=site%3A+forums.x-plane.org+ortho4xp+"ERROR%3A+the+DSF+boundaries+are+out+of+range"

**Comment by OldSubSailor** [comment]
I did not look in the forums.   This just seems to pop up out of nowhere, so I thought it was new. 
A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by OldSubSailor** [comment]
Also, it may have been discussed countless times, but I don’t see countless fixes. 
A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by OldSubSailor** [comment]
I have tried reading what I can of the related posts.  Yes there are many posts, but I have as of yet to find a root cause and a solution for the same.

**Comment by OldSubSailor** [comment]
I can not find a common thread and this issue seems to have been around for some time. Also, it seems to be random. However when I get this error message, if I select only Extract overlays from the Batch build tiles and then click on Batch Build, the process runs as expected and the requisite files are created.
