### ISSUE TITLE
Bug Tile 48-003

### ISSUE THREAD

**Issue by NJ-Poulc** [oscarpilote/Ortho4XP#135]
Impossible to complete the process with bug message below

Step 2.5 : Building masks for tile +48-003 : 
--------ERROR: Mesh file  ./Tiles/zOrtho4XP_+48-003/Data+48-003.mesh absent.
_________________________________________________________________________________________________
Step 3 : Building DSF/Imagery for tile +48-003 : 
--------
ERROR: A mesh file must first be constructed for the tile!y after splitting a segment.
   Splitting subsegment (0.7803597, 0.5709207) (0.780358137985, 0.571076022852) at (0.780358137985, 0.571076022852).

WARNING: Triangle4XP could not achieve the requested quality (min_angle), most probably due to an uncatched OSM error.
It will be tempted now with no angle constraint (i.e. min_angle=0).
   Loading altitudes from DEM file.
   Loading curv_tol geographic weights.
   Computing curvatures from altitudes.
   Constructing Delaunay triangulation by divide-and-conquer method.
   Recovering segments in Delaunay triangulation.
   Internal error in segmentintersection():
   Topological inconsistency after splitting a segment.
   Splitting subsegment (0.7803597, 0.5709207) (0.780358137985, 0.571076022852) at (0.780358137985, 0.571076022852).

ERROR: Triangle4XP really couldn't make it !

If the reason is not due to the limited amount of RAM please
file a bug including the .node and .poly files that you
will find in ./Tiles/zOrtho4XP_+48-003.
_________________________________________________________________________________________________
Step 2.5 : Building masks for tile +48-003 : 
--------
ERROR: Mesh file  ./Tiles/zOrtho4XP_+48-003/Data+48-003.mesh absent.
_________________________________________________________________________________________________
Step 3 : Building DSF/Imagery for tile +48-003 : 
--------
ERROR: A mesh file must first be constructed for the tile!

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/204708-osm-error-at-48-003/
