### ISSUE TITLE
Missing dependency on launch

### ISSUE THREAD

**Issue by Robert-Briggs** [oscarpilote/Ortho4XP#138]
I get the following ModuleNotFoundError when I try to launch.  Please advise.

bob@Roberts-iMac-2 ~ % cd /users/bob/desktop/Ortho4XP-master
bob@Roberts-iMac-2 Ortho4XP-master % python3 Ortho4XP_v130.py
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by d41k4n** [comment]
You did not install the "requests" Python module as per the instructions (or installed it for a different Python runtime).

For further support regarding installation on Mac have a look here:
https://forums.x-plane.org/index.php?/forums/topic/202308-ortho4xp-mac-install-for-dummies-guide-with-pics-v130/
