### ISSUE TITLE
Delete data from custom output

### ISSUE THREAD

**Issue by Gfurst** [oscarpilote/Ortho4XP#142]
I can't tell if just me, but appears to me that the `delete data` function over the world/collection window doesn't work for merged output folders, where all tiles collect into a single scenery folder.
This be a bit troublesome if you re-run tiles with different settings, for example, using a different zoomlevel or provider, will create a whole array of files for texture designation, somewhat related to my issue #141, in the way that you can't tell which files are being used or which ones can be discarded. DSF files aren't removed either, so improving this tool could be very beneficial to handling merged tile scenery.

On that same note, seems that cleanup utilities won't work with merged tiles either, `cleaning_level` in the config, unless I'm misinterpreting how this is supposed to work.

**Comment by oscarpilote** [comment]
True. Grouped tiles have some limitations (maybe because I never used them, which isn't a valid excuse...).
