### ISSUE TITLE
The question of: Bigger resolution vs Number of files

### ISSUE THREAD

**Issue by Gfurst** [oscarpilote/Ortho4XP#143]
So from what I read and understood in terms of scenery development, X-Plane will always load the whole tile at once, and possibly limited loading of nearby tiles. Currently Ortho4XP uses a constant resolution but increased number of images to cover higher zoomlevels, from one level to the next means double the resolution, which is actually squared times the number of images/files (also squared the size of covered area).
This got me wondering if there is any point at keeping a constant size resolution per image, since technically it would be same in terms of load for X-Plane, but could implicitly mean a much higher load under the hood, for example in terms read/write access on disk, fragmentation, and node/file count (not really much of a issue for NTFS, but could be relevant in other systems like linux).
just a few tiles over a region at zoomlevel16 got me around 1500 thousand files, this is each for texture and the meta files for such textures (so in reality about 3 thousand files for region). 
Not only that, but I'm looking into the inherited issue, of having to manually touch up files, which is very often the case ortho imagery, it is better to have the picture whole when looking/sorting issues, than having to go through tenths if not hundredths of individual pictures.
This of course goes along what I proposed #141 here as well, but I'm really inquiring about if there is benefit to having several files as source, if it helps with loading and/or memory usage. Either way, I think regulating the resolution of the output files should be open as a possibility or option.

**Comment by d41k4n** [comment]
The reason for the current implementation  is that X-Planes texture size is limited to 4096 pixel in each dimension.

**Comment by Gfurst** [comment]
Oh well, then there really isn't much we can do.I have thought of custom plugin script for gimp so that we can work on several images at once, but has anyone already tried anything like this? Something to ease post edit?

**Comment by d41k4n** [comment]
AFAIK there were a few topics about that in the official support forum:

 https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/

I suggest you search and/or post any follow-up questions there.
