### ISSUE TITLE
Custom source for OSM data

### ISSUE THREAD

**Issue by Gfurst** [oscarpilote/Ortho4XP#147]
Wouldn't it be useful to be able to pick a custom source for OSM vectoring step? What I'm thinking in case the user already has a more complete database for the region, that he could either individually working in (like for example for World2XPlane), or that he may be working on and want to send back to openstreetmap.

For such cases where OSM data is deficient, Oscar showed us how to manually edit the extracted files on Ortho4XP cache, but I'm wondering if there could be advantages from editing these as whole if the user has the data. There is also the case for pre-emptively download all necessary data, as it means a speed up down the line.

**Comment by oscarpilote** [comment]
Sending back to openstreetmap is touchy and I prefer not to (there has been issues in the past, coastline for your preferred orthophoto source might not be the OSM community's best choice).
3rd party custom source can be used, Ortho4XP will use whatever it finds in the expected cached OSM file names (this was used it intensively while building Norway tiles for zonephotos.org).
