### ISSUE TITLE
Maxar provider

### ISSUE THREAD

**Issue by emiliovfx** [oscarpilote/Ortho4XP#152]
Hello I am trying to add Maxar as a provider but without succes.

Here is what I have currently in Maxar.lay

grid_type=webmercator
url_template=https://services.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe:ImageryTileService@EPSG:3857@jpg/{zoom}/{x}/{-y}.jpg?connectId=_apiKey_&foo=premium

The url was taken from the latest version of OSM where it is working.

**Comment by d41k4n** [comment]
URL us not supported (_apiKey_ needs to be replaced with a valid API key - that's what JOSM does "behind the scenes")
