### ISSUE TITLE
Maxar map additional info found.

### ISSUE THREAD

**Issue by emiliovfx** [oscarpilote/Ortho4XP#153]
Hello I found this additional info for Maxar.

This is working for SAS and it has the token but I don't know how to assemble this info in a .lay file to make it work.

https://services.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe:ImageryTileService@EPSG:3857@jpg/

And then it has a GetURL.script. 

begin 
   ResultURL:=GetURLBase+inttostr(GetZ-1)+'/'+inttostr(GetX)+'/'+inttostr(round(intpower(2,GetZ-1))-GetY-1)+'.jpg? connectId=71a837e4-2609-4496-b5ea-5f0e4fdb020d';
end.

**Comment by d41k4n** [comment]
Pull request created: 
https://github.com/oscarpilote/Ortho4XP/pull/155/files
