### ISSUE TITLE
impossible to build mesh for +48+004

### ISSUE THREAD

**Issue by t2pierre** [oscarpilote/Ortho4XP#156]
"classical" error    
Topological inconsistency after splitting a segment.
[Splitting]subsegment (0.3261488, 0.9797215) (0.326157128476, 0.979329678692) at (0.326157128476, 0.979329678692).

.node and .poly in attachment 

[Archive.zip](https://github.com/oscarpilote/Ortho4XP/files/6496320/Archive.zip)

**Comment by jonaseberle** [comment]
Currently the same for +45+006

[Data+45+006..zip](https://github.com/oscarpilote/Ortho4XP/files/9559400/Data%2B45%2B006.zip)
