### ISSUE TITLE
Base source from OSM downloading failure

### ISSUE THREAD

**Issue by xros** [oscarpilote/Ortho4XP#16]
Starting the UI of Ortho4XP 1.20b, in Provider and Zoomlevel section, select OSM in Base source, it gave me an error log from console:

```
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='a.tile.openstreetmap.org', port=80): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='b.tile.openstreetmap.org', port=80): Read timed out. (read timeout=10)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='c.tile.openstreetmap.org', port=80): Read timed out. (read timeout=10)

```
if you go to http://a.tile.openstreetmap.org/ , it turns out OpenstreetMap has changed its API/page. 

I used `BI` (bing map?) as the base source for instead and it worked. So you mightly update  the openstreetmap api link to use openstreetmap as the base source.

**Comment by d41k4n** [comment]
Based on the [Tile Usage Policy](https://operations.osmfoundation.org/policies/tiles/) it is forbidden to download map tiles from OSM servers in Ortho4XP as it's a publicly distributed app. IMO the only alternative (other than talking to the OSM sysadmins and convincing them to allow an exception for Ortho4XP ) would be to redirect the user to the map view on openstreetmap.org or overpass-turbo.eu via some encoded URL like https://www.openstreetmap.org/#map=11/47.3525/8.7444.

**Comment by artesim** [comment]
Another strategy would be using something like https://openlayers.org/ for the preview, which should be well within the usage policy (I haven't read it, but osm is mentionned right on their front page, as one of their primary tile provider).
Ortho4XP doesn't need osm tiles for anything else than the preview, does it ?

**Comment by xros** [comment]
@artesim I haven't evaluated the amount of the work for intergrating a web browser by switching to QT or GTK from Tkiner. But from the basic lines of UI codes of this repo, I think the work would be a lot. The Ortho4XP's Tkinter UI codes are hard-integrated. We need module-ready for 3rd party implementations.

**Comment by artesim** [comment]
I think so yes, that's kind of what I meant by _"pretty hard to do right now"_ ;-)
