### ISSUE TITLE
Change required to use ALOS Elevation Data (+Added Bjornoya to world_tiles)

### ISSUE THREAD

**Issue by fagidutt** [oscarpilote/Ortho4XP#160]
Hi all
I tried to use ALOS as elevation provider, which didn't work due to a dead link in the Script of Ortho4XP.
I was able to fix this issue and i outlined the process of doing so in this .org-Post. I hope this will help some of you to use higher quality elevation data.
Also i was unable to create elevation data for Bjornoya (small Island south of svalbard) as the world_tiles map didn't include the landmass there. The changed file for it is also to be found, in the last post of that thread. Enjoy the high resolution elevation data :)
Best regards

https://forums.x-plane.org/index.php?/forums/topic/249429-o4xp-does-not-download-elevation-data-for-certain-tiles

**Comment by oscarpilote** [comment]
I have updated the world_tiles.png with yours on my side, will push it for the next update. Could you post the updated link for ALOS ?

**Comment by oscarpilote** [comment]
I have the impression that Opentopograhy does not allow direct download anymore, I have left the provider for compatibility with those having the files already downloaded, but new DEM won't be downloaded. Anyway ALOS was a DSM and for that reason I am not sure it was really worth using it for XP.
