### ISSUE TITLE
NED (from USGS) - USA TILES 1/3" Program No Longer Finds a Valid Download Source

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#164]
I have finally gotten GDAL working with Ortho4XP again. However the tiles created with the custom dem using USGS are awful. Major airports at high ZL are on huge plateaus, and the tile seems to be surrounded by cliffs. 
Example of concern:
Step 1 : Building vector data for tile +34-099 : 

Dealing with airports
    * Recycling OSM data from ./OSM_data/+30-100/+34-099/+34-099_airports.osm.bz2
   
Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+30-100/N34W099_NED13.img from USGS.
    * Min altitude: 0.0 , Max altitude: 0.0 , Mean: 0.0
  
Something is evidently going wrong here. 

I can not recommend using custom dem and USGS at this time.

**Comment by d41k4n** [comment]
Attaching the downloaded .img and perhaps also the output of gdalinfo for that file would be helpful.

**Comment by OldSubSailor** [comment]
I have in the Ortho forums. Headed out of town.

**Comment by OldSubSailor** [comment]
Screenshot that is

**Comment by d41k4n** [comment]
By .img I mean what is mentioned in your comment:

./Elevation_data/+30-100/N34W099_NED13.img

**Comment by OldSubSailor** [comment]
I’ll look for it when I get back then.

**Comment by OldSubSailor** [comment]
This is the full output of the first step Assemble Vector data


Step 1 : Building vector data for tile +32-100 : 
--------

-> Dealing with airports
    * Recycling OSM data from ./OSM_data/+30-100/+32-100/+32-100_airports.osm.bz2
   KABI   Abilene Regional Airport                                     3 runways, lat= 32.41, lon= -99.68
   KDYS   Dyess Air Force Base                                         3 runways, lat= 32.43, lon= -99.84
   ****   Abilene Executive Airpark                                    1 runway , lat= 32.45, lon= -99.62
   ****   Albany Municipal Airport                                     1 runway , lat= 32.72, lon= -99.27
   ****   Arledge Field                                                1 runway , lat= 32.91, lon= -99.74
   ****   Elmdale Airpark                                              1 runway , lat= 32.45, lon= -99.65
   ****   Flying B Ranch Airstrip 35tx                                 2 runways, lat= 32.48, lon= -99.83
   ****   Gregory Simmons Memorial Airport                             1 runway , lat= 32.37, lon= -99.02
   ****   Owen Field                                                   1 runway , lat= 32.25, lon= -99.50
   ****   Ross Planes Airport                                          1 runway , lat= 32.14, lon= -99.16
   ****   Zimmerle Airport                                             1 runway , lat= 32.27, lon= -99.60
   Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+30-100/N32W100_NED13.img from USGS.
    * Min altitude: 0.0 , Max altitude: 0.0 , Mean: 0.0
list index out of range
list index out of range
list index out of range
   Auto-patched 16 runways and 47 pieces of taxiway.
   Flattened 5 helipads.
   Number of edges at this point: 6752
-> Dealing with roads
    * Recycling OSM data from ./OSM_data/+30-100/+32-100/+32-100_big_roads.osm.bz2
    * Checking which large roads need levelling.
    * Recycling OSM data from ./OSM_data/+30-100/+32-100/+32-100_small_roads.osm.bz2
    * Checking which smaller roads need levelling.
    * Buffering banked road network as multipolygon.
      Encoding it.
    * Encoding the remaining primary road network as linestrings.
   Number of edges at this point: 62727
-> Dealing with coastline
    * Recycling OSM data from ./OSM_data/+30-100/+32-100/+32-100_coastline.osm.bz2
   Number of edges at this point: 62727
-> Dealing with inland water
    * Recycling OSM data from ./OSM_data/+30-100/+32-100/+32-100_water.osm.bz2
    * Building water multipolygon.
      Cleaning it.
      Encoding it.
   Number of edges at this point: 119839
-> Inserting edges related to the orthophotos grid
-> Inserting additional boundary edges for gluing
-> Transcription to the files  /Volumes/BigHDD/Custom Scenery/zOrtho4XP_+32-100/Data+32-100.poly and .node

Final number of constrained edges : 234664

Completed in 1m41sec.


And the .poly and .node files







_________________________________________________________________________________________________

**Comment by d41k4n** [comment]
You didn't include any of the requested info yet (.img and/or gdalinfo output for that file).

**Comment by OldSubSailor** [comment]
I said that I can’t find it or the gdalinfo. Where would they be?

I don’t know if it is a temp file that is deleted when the first step id concluded.

**Comment by d41k4n** [comment]
Then that means Ortho4XP didn't download anything - which hints at an issue with the download location for NED (USGS) - likely something has changed server-side.

You could try increasing verbosity to get more info in the message output pane.

**Comment by OldSubSailor** [comment]
I set verbosity to 3, and got a bit more:
Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+30-100/N32W100_NED13.img from USGS.
    Server said 'Not Found'
    Trying alternative naming scheme.
    Server said 'Not Found'
    * Min altitude: 0.0 , Max altitude: 0.0 , Mean: 0.0

I was messing around in Providers/United_States/USGS.lay and the file reads
grid_type=webmercator
url_template=https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryOnly/MapServer/tile/{zoom}/{y}/{x}
imagery_dir=grouped
in_GUI=False

Which may lead to the server not found message perhaps?  
My browser gets as far as MapServer/

**Comment by d41k4n** [comment]
This has nothing to do with imagery downloads so looking at the .lay file is pointless.

However, the verbose output confirms that the DEM download failed with no data found (probably a 404 error returned by the server). The download URL for the DEM is probably hardcoded somewhere and would have to be replaced with an alternative - if that's even possible.

**Comment by OldSubSailor** [comment]
I agree. I think that it would require a return by Oscar who might possibly know how to find and correct the url; if as you say that is even possible. Perhaps the USGS has blocked it?

**Comment by d41k4n** [comment]
You keep mixing up imagery and elevation data downloads. The 400 return code (= bad request) is about the USGS imagery provider, which isn't necessarily related to the elevation data in scope here (unless the same server provides both data types).
Unfortunately there is no other useful information printed in the message pane except "Not found" which usually translates to the HTTP response code 404.

**Comment by OldSubSailor** [comment]
I believe that it is both.

**Comment by d41k4n** [comment]
Well, congratulations, you found the location in the code that needs to be modified using an alternative public download source - if there is one.

**Comment by OldSubSailor** [comment]
https://aws.amazon.com/s3/
Gets to a real page but of what use?  The rest of the url link seems to be full of XML text and no data remaining. Of course, I know nothing of XML. StagedProducts downloads an empty file.

**Comment by oscarpilote** [comment]
Made the necessary changes in my local branch for the next update.
