### ISSUE TITLE
Linux Install Instructions

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#170]
Has anyone visited these instructions and verified them as current and correct and with regard to 1" USGS in particular?  I am getting some negative feedback on the X-Plane forums regarding flat terrain.

**Comment by jonaseberle** [comment]
You mean https://github.com/oscarpilote/Ortho4XP/blob/master/Install_Instructions.txt I guess.
These worked reasonably good for me (Manjaro).

I don't understand your 1" USGS reference, though.
