### ISSUE TITLE
What is the best way to add delay between http requests?

### ISSUE THREAD

**Issue by kunajk** [oscarpilote/Ortho4XP#175]
Hello, Im trying to add source, that demands small delays between requests. Wherere is best place to put sleep command?

**Comment by oscarpilote** [comment]
There used to be such an option, but it got deprecated when downloads were multi-threaded. Do you really need a timer between two consecutive http requests or just some kind of bandwidth limit ? (the latter could be added, the former probably not)

**Comment by anthraxn8b** [comment]
@kunajk, sorry in advance, but until today most of the time I saw a pause/sleep/... the reason was bad code.
Maybe you could give me a hint so that I may understand what you try to do - and maybe can come up with an alternative...

**Comment by kunajk** [comment]
@anthraxn8b Hey, no problem. I want to add sleep between http request because without it server bans my IP
