### ISSUE TITLE
Error installing pyproj on Mac M1

### ISSUE THREAD

**Issue by foghornleghorn-eng** [oscarpilote/Ortho4XP#177]
brew install proj

was required before the setup would complete.

ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/0d/t27wtpjn4gj46xn_h_4gcp180000gn/T/tmpgf0hgz7f
       cwd: /private/var/folders/0d/t27wtpjn4gj46xn_h_4gcp180000gn/T/pip-install-0c6mouyp/pyproj
  Complete output (1 lines):
  proj executable not found. Please set the PROJ_DIR variable. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/0d/t27wtpjn4gj46xn_h_4gcp180000gn/T/tmpgf0hgz7f Check the logs for full command output.

**Comment by foghornleghorn-eng** [comment]
also 

brew install python-tk

**Comment by d41k4n** [comment]
Is that still an open issue?

If so, have you looked at the recent comments in https://forums.x-plane.org/index.php?/forums/topic/202308-ortho4xp-mac-install-for-dummies-v130-high-sierra ?
