### ISSUE TITLE
Get Ortho4XP to generate completely white water masks?

### ISSUE THREAD

**Issue by loop54-christoffer** [oscarpilote/Ortho4XP#182]
I don't particularly like the X-Plane water rendering, and I don't care much for it either. Also, it causes some problems with flooding in some tiles, so one could say it would improve my life to get rid of it.

I figured out one way to do it: paint over all the water masks with 0xfff. This is fairly easy to do by just copy-pasting a white image over all the mask files, and then re-running the last DSF build step of Ortho4XP. But

(a) Can I get Ortho4XP to do this for me automatically? or

(b) Is there a better way to accomplish my goal? (I.e. not have X-Plane render water over the already nice-looking ortho scenery.)

**Comment by fralbo** [comment]
Even on xp12? Didn't look at it yet but I read that water rendering has been reworked.

**Comment by oscarpilote** [comment]
There used to be a no XP water option, which got removed at some point (for 1.30 maybe).
Depending on how the bathymetry issue evolves, I'll consider adding it back.
