### ISSUE TITLE
X-Plane 12 support request

### ISSUE THREAD

**Issue by eddo888** [oscarpilote/Ortho4XP#184]
Hi, just asking could you please tell me if this will support x-plane 12 ?

**Comment by RotationMatrix** [comment]
It is working on X-Plane 12 for me. No issues so far.

**Comment by fralbo** [comment]
Even around water?
Where do you install it from?

**Comment by RotationMatrix** [comment]
Yes even around water seems to work. This is a quick ZL17 tile I made from Bing around Whidbey Island (KNUW).

![F-14D - 2023-01-15 01 11 32](https://user-images.githubusercontent.com/52428419/212502916-e548b6e4-8319-43a6-b045-9a10e602f8df.png)

**Comment by Rastuasi** [comment]
No it's not fully supported around water yet, the person saying it does isn't looking at proper issue
