### ISSUE TITLE
mesh viewer

### ISSUE THREAD

**Issue by hutchij** [oscarpilote/Ortho4XP#19]
Is it possible to view the mesh generated by Ortho4XP? The manual has some screen shots which seem to show the mesh. I wonder how this was done.

**Comment by d41k4n** [comment]
https://fileinfo.com/extension/mesh
https://forums.x-plane.org/index.php?/forums/topic/148295-krabi-mesh-with-orhtotiles/&do=findComment&comment=1412127

**Comment by hutchij** [comment]
Thanks. I'm on v120b on windows. WHat's the easiest way to update my install to the latest stable?

**Comment by d41k4n** [comment]
There is no clear update path from 1.20b to 1.30, so I think it's best to start with a separate installation.

BTW: A pretty easy way of visualizing any parts of the mesh is by opening the Preview / Custom ZL window, generate a preview using any provider/ZL, marking a custom area and using the function "Extract mesh". This will generate a Wavefront Object (.obj) which can be imported for visualization in most 3D modeling tools (i.e. I use MeshLab for this purpose).

**Comment by oscarpilote** [comment]
.mesh files can be opened directly with the "medit" executalble by Pascal Frey. I use it all the time (although on linux) for that purpose.
