### ISSUE TITLE
Problems Downloading Data for Sydney, Australia

### ISSUE THREAD

**Issue by ilikefrogs101** [oscarpilote/Ortho4XP#191]
I tried downloading the satellite data for sydney airport area but I get
"index out of range
index out of range
index out of range
index out of range
index out of range
index out of range
index out of range
index out of range
index out of range
index out of range
index out of range"
along with the list of airports then it says it has downloaded the data seemingly quickly but it does not actually appear downloaded when you check the folder

**Comment by d41k4n** [comment]
Try setting road_level=0.

See also [here](https://forums.x-plane.org/index.php?/forums/topic/277856-triangle4xp-really-couldnt-make-it-cant-generate-34151-tile-sydney/&do=findComment&comment=2456484).
