### ISSUE TITLE
All terrain at EKVG removed with autoortho installed.

### ISSUE THREAD

**Issue by Awemeter** [oscarpilote/Ortho4XP#192]
EKVG is a very mountainous airport but when used with ortho4xp it becomes flat.

**Comment by d41k4n** [comment]
You need to be more precise what you mean by "removed with autoortho installed" and "flat".

E.g. is the whole tile affected or only the airport perimeter of EKVG? Does this only occur when autoortho is installed? If not, what were your Ortho4XP parameters and message outputs when creating the tile?

Attaching screenshots and a log.txt would be helpful.
