### ISSUE TITLE
Depreciation errors with GNU/Linux

### ISSUE THREAD

**Issue by CarlBcx** [oscarpilote/Ortho4XP#196]
I have been using Ortho4xp for several years and I take this opportunity to thank you for giving us the benefit of this remarkable tool.

I'm on GNU/Linux with X-Plane 12.
Since the XUbuntu 23.04 update (Kernel 6.2.0-20) I got different "depreciation" errors.
Searching a bit I modified in the code some "numpy" as indicated by python, for example "numpy.bool" replaced by "bool".
By correcting these errors it works but I'm worried about the future because in the console there are different alerts like "ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead."

I don't think many of us use Ortho4XP with GNU/Linux, let alone the latest version.
But this inevitably risks causing problems quickly. Already for those who have upgraded to 23.04 and who don't know enough to make the code changes I had to make.

So, if it can help, here is attached my log as well as the return of the console made today with the compilation of a tile with BI and in 17.
I specify that I do not make the Overlay because I use those of Simheaven.

Thank you in advance for your return.
carl
[20250520_Ortho4XP.log](https://github.com/oscarpilote/Ortho4XP/files/11522166/20250520_Ortho4XP.log)
[20250520_Ortho4XP_Console.txt](https://github.com/oscarpilote/Ortho4XP/files/11522167/20250520_Ortho4XP_Console.txt)
[20250520_Ortho4XP_Screen log.txt](https://github.com/oscarpilote/Ortho4XP/files/11522168/20250520_Ortho4XP_Screen.log.txt)

**Comment by CarlBcx** [comment]
For a few days I have crashes in XPlane, a small window that appears with the errors:
"flt_to_str NaN"
"v=NaN"

I hadn't made the connection but I believe it happens on tiles made with Ortho4XP.
So I think that despite my changes in the code there are still errors that produce these crashes.

I hope this can be fixed quickly and I am available if help is needed for testing.

**Comment by Relms12345** [comment]
@CarlBcx You can try using this fork which fixes the deprecation errprs: https://github.com/ekaats/Ortho4XP

**Comment by CarlBcx** [comment]
Thank you @Relms12345 , I will try.

**Comment by CarlBcx** [comment]
I have tryed the fork and I have no alerts or errors with it.
Thanks again for help !
