### ISSUE TITLE
download only .jpeg files

### ISSUE THREAD

**Issue by betampona** [oscarpilote/Ortho4XP#198]
Hello, I would like to know if it is possible to download only the .jpeg tiles. No vector data, 3Dmesh, draw water mask.
Thanks for your help.

**Comment by d41k4n** [comment]
Please use the [official Ortho4XP forum](https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/) to ask usage questions. This GitHub issue tracker is for reporting bugs only (i.e. unexpected bahavior).
