### ISSUE TITLE
MSVCP120.DLL

### ISSUE THREAD

**Issue by Manfredo64** [oscarpilote/Ortho4XP#211]
Hello,
Wenn ich Photokacheln herunter lade, bekomme ich die Fehlermeldung MSVCP120.dll nicht gefunden.
Habe Python und Visual Studio 2022 installiert, funktioniert auber irgendwie nicht.

Vielen Dank für Tipps

**Comment by oscarpilote** [comment]
This should probably best be asked on a (german) forum. Probably that dll is missing on your windows machine.
