### ISSUE TITLE
Bad zipfile

### ISSUE THREAD

**Issue by Cactusmies** [oscarpilote/Ortho4XP#225]
I was trying to make a ortho tile for KLAX using the sfd scenery and the orthopatch that comes with it, but it didnt even get to the patching phase before saying "bad zipfile". I then tried doing it without the orthopatch to see if that was the reason for it not working but ended with the same result. I find this weird as i was able to make a orthotile for sfd's EDDM using the orthopatch just yesterday with no issues. I also tried Sfd's KABQ with the orthopatch and that also worked. I then tried to create just a regular tile above LA but it gave me the same warning. I have the latest stable python release and i tried a couple of older ones aswell. C++ is also installed and up to date and i did try older versions of that aswell but it didnt help. I am using the latest 1.30.
<img width="1920" alt="Desktop Screenshot 2024 03 05 - 23 47 16 60" src="https://github.com/oscarpilote/Ortho4XP/assets/134816424/d36e4d5f-1c6a-47e5-bbcc-31c702d39087">

**Comment by d41k4n** [comment]
I assume you are using the default DEM source? 

Looks like you either have corrupted tmp data for that tile or there is an issue with downloading from viewfinderoanoramas.org.

I suggest to delete the tmp folder (if not already empty) and retry.

If the error persists it would help if you set verbosity=3 then rerun from step 1 and include the full output messages.

**Comment by Cactusmies** [comment]
> I assume you are using the default DEM source?
> 
> Looks like you either have corrupted tmp data for that tile or there is an issue with downloading from viewfinderpanoramas.org.
> 
> I suggest to delete the tmp folder (if not already empty) and retry.
> 
> If the error persists it would help if you set verbosity=3 then rerun from step 1 and include the full output messages.

I tried it with Bing Google and ARC. I'll try those tomorrow when i have time. Thank you for responding and helping!

**Comment by d41k4n** [comment]
Those are imagery providers and IMO totally irrelevant to your error.

**Comment by Cactusmies** [comment]
> Those are imagery providers and IMO totally untelated to your error.

You're tips worked for LA. I deleted the temp file and it worked. But now im facing an issue with hong kong... the same issue which i can't seem to fix using your tips. 
<img width="1920" alt="Desktop Screenshot 2024 03 10 - 00 34 58 85" src="https://github.com/oscarpilote/Ortho4XP/assets/134816424/ef595d0f-9826-4655-8fa8-654ee728109d">

**Comment by d41k4n** [comment]
I can only repeat what I already said:

If the error persists it would help if you set verbosity=3 then rerun from step 1 and include the full output messages.

**Comment by d41k4n** [comment]
I was able to reproduce the error - it seems related to an issue with viewfinderpanoramas.org where a corrupted zip file is downloaded.

The following is the download URL of the zip archive that is supposed to contain all elevation rasters in .hgt format for the HongKong region:

https://viewfinderpanoramas.org/dem3/F49.zip

When I download this via browser I'm unable to open it via 7-Zip or any other compression tool.

For now, the only workaround is to use a different DEM source for tiles in that region or find a place that provides elevation data in .hgt format and manually download it into the appropriate subfolder (+20+110) under Elevation_data.

**Comment by d41k4n** [comment]
Seems like it's working again - at least I'm no longer able to reproduce the problem now.

**Comment by Cactusmies** [comment]
> Looks like it was a temporary issue with viewfinderpanoramas.org - at least I'm no longer able to reproduce the problem now.

Thank you so much for your help! I'll try to again later today. You have been beyond helpful and kind.
