### ISSUE TITLE
Bug: Empty UI on MacOS

### ISSUE THREAD

**Issue by scriptPilot** [oscarpilote/Ortho4XP#236]
On MacOS 14.4 @ MacBook M1:

Error log:

````
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2024-03-17 02:35:09.783 Python[99908:1117833] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
````

Screenshot:

<img width="1093" alt="Bildschirmfoto 2024-03-17 um 02 36 06" src="https://github.com/oscarpilote/Ortho4XP/assets/19615586/64c123f3-04e8-48d1-bd59-f90ff00c07ac">

**Comment by w8sl** [comment]
See this comment for updated install instructions:
https://github.com/oscarpilote/Ortho4XP/issues/210#issuecomment-1795356672

**Comment by scriptPilot** [comment]
Thanks for the step by step, I will follow the setup process again.

Would be a real improvement to have a simple Docker image available, running well on all platforms :-)
https://github.com/oscarpilote/Ortho4XP/issues/188
