### ISSUE TITLE
Error: Absent earth nav data

### ISSUE THREAD

**Issue by scriptPilot** [oscarpilote/Ortho4XP#239]
Following the [install guide for MacOS](https://github.com/oscarpilote/Ortho4XP/issues/210#issuecomment-1795356672) I found the following error in the logs, but the named config field is not available in the config window:

```
ERROR: file  Earth nav data/+40+000/+45+007.dsf absent.
Recall that the overlay source directory needs to be set  in the config window first.
```

**Comment by d41k4n** [comment]
The related config parameter is called custom_overlay_src and you either specified a wrong path or there is no DSF available for the tile in the subfolder mentioned in the error message.

**Comment by scriptPilot** [comment]
With [simHeaven](https://simheaven.com/xp11-sceneries/) I understand that overlays should not be created.
So can I ignore the error message or does it have any impact on the tile creation?

**Comment by d41k4n** [comment]
It depends where you fly. The Simheaven manual has more info on that.
