### ISSUE TITLE
I noticed this error message on a different OS but that fix did not work for macOS. . .

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#241]
I reinstalled everything on my old 2017 iMac, Ventura 13.6, and am now getting a **No module named 'skfmm"** error message.  I tried the install scikit-fmm , but no joy.  
Python 3.11

but same for Python 3.9
% pip3.11 list
Package            Version
------------------ --------
certifi            2024.2.2
charset-normalizer 3.3.2
idna               3.6
numpy              1.26.4
pillow             10.2.0
pip                24.0
protobuf           4.25.3
pyproj             3.6.1
requests           2.31.0
Rtree              1.2.0
scikit-fmm         2023.4.2
setuptools         69.1.0
shapely            2.0.1
urllib3            2.2.1
wheel              0.42.0

**Comment by w8sl** [comment]
pip3.11 install scikit-fmm

**Comment by OldSubSailor** [comment]
Please note above that I tried that, and it shows up in the listing.

**Comment by OldSubSailor** [comment]
crossing wires here, I did all that prior to posting

**Comment by OldSubSailor** [comment]
I was using a build that was about 2 years old with no issues. but just had to play and alas trashed the old one by mistake.

**Comment by w8sl** [comment]
Try to comment out "import skfmm" in O4_Mask_Utils.py and see if everything else is working. Just don't use distance masks

**Comment by OldSubSailor** [comment]
I went back to my branch (https://github.com/OldSubSailor/Ortho4XP) and got the older version that works

**Comment by OldSubSailor** [comment]
I understand what you are saying, however, what is needed is a real fix to that issue. We have had to comment out things in the past. The directory skfmm is in the site packages directory on the iMac.

**Comment by w8sl** [comment]
...and see if everyting else is working or if it is skfmm problem

**Comment by OldSubSailor** [comment]
Ok, there are odd things going on with it commented out. It starts up then I got as far as the Build Imagery / DSF and things went south with dsf and the tile not being active.  And I do seem to have a mess of python versions floating around on this iMac

**Comment by OldSubSailor** [comment]
I went deep into the iMac and got rid of all versions (I even had 3.12)of Python except 3.9. I uncommented the import line and called Ortho and it came up as expected. It is getting past this old man's bed time so I did not try running it tonight.  Hopefully, I will have time for that tomorrow.

**Comment by w8sl** [comment]
Default Python 3.9 + 2 versions installed via Homebrew are normal these days. It is easy to control by brew link, brew unlink or brew uninstall commands. The only problem is Python from org.
Ortho4XP 1.40 requires XP-12 and configuration variable "custom_overlay_src" should be set to: "../X-Plane 12/Global Scenery/X-Plane 12 Global Scenery" directory in order to fetch bathymetry data. (X-Plane 12 Demo Areas are also working with tile +45-123). 
The only visible difference between 1.30 and 1.40 is 3D water. There is an option "water-tech: XP11+bathy" which actually is 3D water + XP11 style overlay.

**Comment by OldSubSailor** [comment]
I am glad that you pointed that out. I did buy XP 12, but it truly taxes this iMac, so I do not have it installed. So I take it that I actually am at a stopping point seeing as how I only have XP 11 (and simHeaven which works pretty nicely with Ortho4).

**Comment by OldSubSailor** [comment]
Well, it still will not finish building a tile. I get this at the end:
  Converting orthophoto(s) to build texture 108144_63280_GO218.dds.
 *Download of textures completed.
 *DDS conversion of textures completed.
 *Activating DSF file.
ERROR : could not rename DSF file, tile is not actived.

Because it is in XP 11 perhaps?

**Comment by w8sl** [comment]
I think so. You may test with Portland tile an XP12 demo

**Comment by OldSubSailor** [comment]
I went back to the older version.  I had no issues making a tile yesterday day. Today after all the messing around I got the on the terminal. Ortho appeared to lock up or stopped.
 File "/Users/trav/Ortho4XP-master/./src/O4_Vector_Map.py", line 138, in include_airports
    APT.smooth_raster_over_airports(tile,dico_airports)
  File "/Users/trav/Ortho4XP-master/./src/O4_Airport_Utils.py", line 429, in smooth_raster_over_airports
    for polygon in full_area:
TypeError: 'MultiPolygon' object is not iterable

I uninstalled Homebrew and etc and reinstalled, no joy.

**Comment by scriptPilot** [comment]
Same for me. Downloaded the current master branch, applying the MacOS installation steps in order but receive an error when re-creating a tile: `ERROR : could not rename DSF file, tile is not actived.`

**Comment by w8sl** [comment]
I have yesterday updated instructions previously posted on closed issue regarding install on Sonoma. Step 6 is necessary to run 1.30. (Removing app extension is only necessary on Sonoma). You can also test my unofficial branch: Progressive_XP11
(nvcompress and Triangle4XP without .app extension are included, work on Ventura also)

**Comment by OldSubSailor** [comment]
I was back to Python 3.9

**Comment by w8sl** [comment]
Thank you again! Your old pull request was first that worked. Homebrew was far from perfect at the time.

**Comment by OldSubSailor** [comment]
To sum it up then.  It was a combination of the Python.org version and my X-Plane 11 with your version 1.40 of Ortho4. We had some incompatible versions of things crashing into each other. 
For Ventura:
X-Plane 11 my old 2021 Ortho4XP will work with Python3.11 and the listing as shown below (installed as per the instructions **And yours**):
% pip3.11 list
Package            Version
------------------ --------
certifi            2024.2.2
charset-normalizer 3.3.2
idna               3.6
numpy              1.23.5
pillow             10.2.0
pip                24.0
protobuf           4.25.3
pyproj             3.6.1
requests           2.31.0
Rtree              1.2.0
setuptools         69.1.0
Shapely            1.8.1
urllib3            2.2.1
wheel              0.42.0

_**SO WE SHOULD BE ABLE TO CLOSE NOW?**_

**Comment by w8sl** [comment]
Looks perfect.
You are welcome!
