### ISSUE TITLE
NV compress sys error

### ISSUE THREAD

**Issue by atom1955** [oscarpilote/Ortho4XP#242]
specific error reads "MSVCR120.dll was not found" when attempting to build the scenery tile.  New install of Ortho4Xp version 1.30 Binary for windows.

**Comment by atom1955** [comment]
Apologies, the missing file is MSVCP120.dll

**Comment by w8sl** [comment]
Cannot give a better explanation than internet search for:"missing MSVCP120.dll"

**Comment by atom1955** [comment]
I took your advice, and searched for the error via the internet.  I ended up having to re-install my MS C++ Files, which fixed the problem.  Thanks for your response.
