### ISSUE TITLE
v1.40 12.10 freeze/crash.

### ISSUE THREAD

**Issue by domrnet** [oscarpilote/Ortho4XP#253]
Now using 12.10 the sim crashes or freezes up when using autho that has sea/ocean in the tile when using autho made from version 1.40. Tiles from v1.30 with sea are ok as far as I tested.

I get no log because of the freeze so cannot attach it.

**Comment by shizumaat** [comment]
FWIW I've tested a number of tiles generated with v1.4 and bathymetry and they all worked fine. Some that had really bad flickering in the water along the coast now look much better, although there seems to be a bit harsher edge to the water at the beach.

**Comment by domrnet** [comment]
Great that's good to know. I wonder if it's because I only updated the tiles previously when running V1.40 on them instead of re making them. I will re make some from scratch and see if that is the issue.

**Comment by emiliovfx** [comment]
I can confirm that I've made so far a bunch of tiles with bathymetry, not regenerating them but just using the previous tile config without any problems.   All the tiles are working in XP12.0.9 and 12.1 beta without an issue.

What are your water mask settings?

**Comment by domrnet** [comment]
> > Now using 12.10 the sim crashes or freezes up when using **autho** that has sea/ocean in the tile when using **autho** made from version 1.40. Tiles from v1.30 with sea are ok as far as I tested.
> 
> What do you mean by "autho"? Is this a typo or are you referring to [autoortho](https://github.com/kubilus1/autoortho) by any chance?

It's a typo

**Comment by domrnet** [comment]
> I can confirm that I've made so far a bunch of tiles with bathymetry, not regenerating them but just using the previous tile config without any problems. All the tiles are working in XP12.0.9 and 12.1 beta without an issue.
> 
> What are your water mask settings?

Current settings are
`verbosity=1
cleaning_level=1
overpass_server_choice=random
skip_downloads=False
skip_converts=False
max_convert_slots=4
check_tms_response=True
http_timeout=10.0
max_connect_retries=5
max_baddata_retries=5
ovl_exclude_pol=[0]
ovl_exclude_net=[]
custom_scenery_dir=
custom_overlay_src=/mnt/FG/X-Plane 12/Global Scenery/X-Plane 12 Global Scenery
apt_smoothing_pix=9
road_level=1
road_banking_limit=0.5
lane_width=5.0
max_levelled_segs=100000
water_simplification=0.0
min_area=0.001
max_area=200.0
clean_bad_geometries=True
mesh_zl=19
curvature_tol=2.0
apt_curv_tol=0.5
apt_curv_ext=0.5
coast_curv_tol=1.0
coast_curv_ext=0.5
limit_tris=0
hmin=0.0
min_angle=10.0
sea_smoothing_mode=zero
water_smoothing=10
iterate=0
mask_zl=14
masks_width=100
masking_mode=sand
use_masks_for_inland=False
imprint_masks_to_dds=True
distance_masks_too=False
masks_use_DEM_too=False
masks_custom_extent=
cover_airports_with_highres=ICAO
cover_extent=0.5
cover_zl=19
water_tech=XP12
ratio_bathy=1.0
ratio_water=0.25
overlay_lod=25000.0
sea_texture_blur=0.0
normal_map_strength=1.0
terrain_casts_shadows=False
use_decal_on_terrain=False`

Just re making all the tiles that I had previously updated so lets see from that unless you see something really amiss here. Was all working fine with  XP12.9

**Comment by emiliovfx** [comment]
This is what is giving me the best results so far.

Masks for inland.  True
Imprint masks to dds.  False

**Comment by domrnet** [comment]
if this current run doesn't work out I will give it a try. thanks

**Comment by domrnet** [comment]
Whole of UK redone.. Same result.

**Comment by domrnet** [comment]
Ok. When I re-ran I didn't completely delete everything. I tested one tile now by deleting everything for it as  though it never existed. Built it new and no issue. So mass delete done and My PC will be busy as I sleep tonight. I will feedback results.

**Comment by domrnet** [comment]
Ok update to close there must have been something wrong with the tiles. After a complete wipe of my UK tiles and a new build there are zero issues. My frames are actually slightly up so something was a well hidden issue till now.
