### ISSUE TITLE
Patch data being overruled

### ISSUE THREAD

**Issue by shizumaat** [oscarpilote/Ortho4XP#274]
I sometimes run into trouble when working on a custom OSM patch for use with Ortho4XP where the generated tile appears to ignore and/or override the altitude I've specified in my patch. This primarily happens along runways, taxiways, and aprons. It seems like some sort of smoothing is occurring after the patch is applied, and that when this happens it's referring to the original altitude rather than the one specified in the patch. For example, if you look at KATL Atlanta airport, the Southern most runway, 10/28 has a tunnel where the freeway passes under it. If you simply add a rectangle over the runway to try and flatten it, the result I'm getting is on the grass at the edge of the runway it's the altitude specified in my patch, but the runway itself is dramatically lower and smoothed. If I attempt to add a slope (rectangle with altitude_low and altitude_high parameters) the result is a crazy series of steps. 

Anyone run into this and have any solutions before I start trying to hack the mesh_utils.py?

**Comment by d41k4n** [comment]
See https://forums.x-plane.org/index.php?/forums/topic/310583-osm-patches-being-overwritten-in-some-cases/&do=findComment&comment=2739716
