### ISSUE TITLE
Syntax error on Win10

### ISSUE THREAD

**Issue by fralbo** [oscarpilote/Ortho4XP#28]
Hello,

When I try to execute it on Win10, I get the following error:

	PS D:\Ortho4XP-1.30> .\Ortho4XP_v130.py
	Traceback (most recent call last):
	  File "D:\Ortho4XP-1.30\Ortho4XP_v130.py", line 9, in <module>
	    import O4_Imagery_Utils as IMG
	  File ".\src\O4_Imagery_Utils.py", line 555
	SyntaxError: Non-ASCII character '\xc2' in file .\src\O4_Imagery_Utils.py on line 555, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Any idea?

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/156790-problem-with-v130-on-windows/&tab=comments#comment-1478475
