### ISSUE TITLE
is this still current?

### ISSUE THREAD

**Issue by xpd259** [oscarpilote/Ortho4XP#3]
Hello!

thank you for such an awesome project. but is this still current 
I ask as I find using github easier to keep track of than dropbox
for changes etc

regards
Dick Thomas

**Comment by rustamgaifullin** [comment]
Hello,

actually the same for me I prefer github over dropbox, but it looks like that latest version is in dropbox.

**Comment by dyoung522** [comment]
Yes!

We've re-organized the code and, In fact, the current "master" branch now points to the same code that's found on @oscarpilote's dropbox account. 

We've also created a v120 release here as well, so feel free to download it from the releases section.

Note: There's not likely to be any changes to the v120 code, as most of the effort it going into the new v130 release (stay tuned!)
