### ISSUE TITLE
batch  build doesn't care about custom zoom level areas

### ISSUE THREAD

**Issue by fralbo** [oscarpilote/Ortho4XP#30]
I didn't see in the [manual](http://download.jirikocman.cz/Manual.pdf) if batch build should process it or not but according to this [post](https://forums.x-plane.org/index.php?/forums/topic/126187-batch-building-of-custom-level/) it seems it doesn't work.

I prepared several tiles at base zoom level 16 and I defined few areas in these tiles with ZL18 and ZL19.

I made a batch build and all tiles have BI16.dds files only in `textures` folder.

So I selected one of these tiles and just hit `All in one` button in the main window.
Then BI18 and BI19 files where generated.

Would it be possible to also do that job in batch build?

**Comment by d41k4n** [comment]
After editing the custom ZL did you hit the button "Save & exit" and then also saved the tile specific config using the "Write tile cfg" button in the config window for each tile?

**Comment by fralbo** [comment]
Yes I did it and as I explained, I first hit `batch build`, after defining some tiles, I then looked at on result folder to see only BI16 downloaded jpeg.
So I selected one the previously defined tiles, I verified that the custom ZL areas were still defined on the map and just hit `All in one` button in the main window. That way BI18 and BI19 dds were donwloaded.

I did the same for all other tiles i.e. select it on the map (yellow square) and then hit `All in one` to add missing BI18 and BI19 dds.

**Comment by d41k4n** [comment]
Did you tick option "Read per tile cfg" before starting your batch build?

**Comment by fralbo** [comment]
Yes I did.

**Comment by oscarpilote** [comment]
One of the lasts commit solved that issue.
