### ISSUE TITLE
Real World Photo Scenery Question

### ISSUE THREAD

**Issue by DemonRem** [oscarpilote/Ortho4XP#36]
I using Imgery BI zoom Level 16

on area LLBG after removing my customize LLBG by IXPT , and I got the original area by XPlane

**Comment by d41k4n** [comment]
Sounds like this is unrelated to Ortho4XP and rather an issue with your scenery order. 

Besides, I think the better place to ask for support in the context of Ortho4XP would be here:

https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/158778-creation-real-scenery-how-to/
