### ISSUE TITLE
print(line.decode("utf-8")[:-1])

### ISSUE THREAD

**Issue by benjaminrc78** [oscarpilote/Ortho4XP#37]
C:\Ortho4XP>python Ortho4XP_v130.py
ERROR: Providers/O4_Custom_URL.py contains invalid code. The corresponding providers won't probably work.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File ".\src\O4_Tile_Utils.py", line 162, in build_tile_list
    MESH.build_mesh(tile)
  File ".\src\O4_Mesh_Utils.py", line 371, in build_mesh
    print(line.decode("utf-8")[:-1])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 28: invalid continuation byte

**Comment by d41k4n** [comment]
Can't reproduce this on my end.

Some people have reported this error with v120b, too:

https://forums.x-plane.org/index.php?/forums/topic/150701-ortho4xp-broblem/&do=findComment&comment=1430717

I suspect this might be related to some Windows locale/language settings.

**Comment by benjaminrc78** [comment]
I try to reinstall all, and the first time works, but the next give the error again !
I try to delete OSM_data and other .. but now work.

**Comment by oscarpilote** [comment]
"Fixed" by introducing a try/except statement, although I do not understand what was the cause on the user side.

**Comment by d41k4n** [comment]
The cause was likely a non-standard-latin character in the base folder path - like in this case:
https://forums.x-plane.org/index.php?/forums/topic/150701-ortho4xp-broblem/&do=findComment&comment=1495366
