### ISSUE TITLE
OSM tile servers block rapid requests

### ISSUE THREAD

**Issue by NCRonB** [oscarpilote/Ortho4XP#4]
When I try to use OSM as a source, I quickly start getting "request timed out" errors from the OSM tile servers. It seems they're blocking my requests, and based on their usage policy, I can see why. Ortho4XP spawns many threads to fetch tiles with no delays (except when there's an error).

It would be nice to have a "be polite to tile servers" option to slow down tile fetching requests and avoid being blocked.

**Comment by d41k4n** [comment]
OSM was never meant to be used as a source for generating tiles, only as preview for defining custom ZL.

https://forums.x-plane.org/index.php?/forums/topic/115382-btileopenstreetmaporg-timed-out-error/&do=findComment&comment=1157226

**Comment by NCRonB** [comment]
I see. Thanks.

I imagine other tile sources would prefer they not be hit with rapid requests as well. Perhaps an optional throttle feature would be helpful anyway for those of us who aren't in a hurry and would like to play nice, particularly for batch converting large areas.
