### ISSUE TITLE
Providers/O4_Custom_URL.py contains invalid code

### ISSUE THREAD

**Issue by httpRick** [oscarpilote/Ortho4XP#40]
ERROR: Providers/O4_Custom_URL.py contains invalid code. The corresponding providers won't probably work.

The code used for the patch on the "https://forums.x-plane.org/index.php?/forums/topic/155224-error-within-providerso4_custom_urlpy/" forum unfortunately does not work.

https://imgur.com/DycXHZj

**Comment by oscarpilote** [comment]
Fixed with the actual file version (prior was a stub)
