### ISSUE TITLE
EU-DEM v1.1

### ISSUE THREAD

**Issue by alexandar-m** [oscarpilote/Ortho4XP#41]
Your App is great tool, thanks!

Is it possible to use Copernicus EU-DEM v1.1 TIF elevation data from
https://land.copernicus.eu/imagery-in-situ/eu-dem/eu-dem-v1.1/

And also is there any way to export real GIS data from QGIS (roads, railroads, houses, buildings, parks, parkings...)

With those 2 things and your app it would be perfection!

**Comment by d41k4n** [comment]
You can feed Ortho4XP any DEM as long as it is in either .hgt or .tif (geotiff) format and uses web mercator projection (EPSG:3857).

For the second point the current (and likely future) answer is no. There are other tools which create  overlays from third-party data (mainly OSM) and which might be able to fulfill that requirement in a future release ([W2XP](https://forums.x-plane.org/index.php?/files/file/33450-world2xplane-application/), [OSM2XP](https://forums.x-plane.org/index.php?/forums/topic/151582-osm2xp-30/). In fact, W2XP 1.x already does that but it was never released to the public...

**Comment by oscarpilote** [comment]
Only a slight detail : DEM files used as input to Triangle4XP need to be in EPSG:4326 (geographic coordinates). EPSG:3857 is the one that is used for Orthophotos.
Also, if you have gdal python module installed, about any file format for the DEM is fine.

**Comment by d41k4n** [comment]
Thanks for pointing that out! This always confuses the hell out of me (and probably with many others) 😁

May I ask what's the reason for not using the same projection for ortho and DEM?

**Comment by alexandar-m** [comment]
Thanks for info.
Solved one more problem.. did not generated yOrtho4XP_Overlays for every Tile i needed to include in sim. Now ortho and autogen are working and folders are in this order.

Custom Scenery
/Airports
/OpenSceneryX
/R2_Library
/simHeaven_X-Europe-1-extras
/simHeaven_X-Europe-2-scenery
/simHeaven_X-Europe-3-network
/yOrtho4XP_Overlays
/zOrtho4XP...
/zzz_hd_global_scenery4

Do i need to add any specific elevation file using HD V4 package?

**Comment by d41k4n** [comment]
No, elevation is irrelevant for overlay extraction.

**Comment by oscarpilote** [comment]
> May I ask what's the reason for not using the same projection for ortho and DEM?
X-Plane uses EPSG:4326 for its node coordinates, and therefore better stick to it for .mesh and DEM.
Textures in the end are referenced with their (s,t) (between 0 and 1) coordinates, so in any case there is a mapping to be done between node coordinates and textures coordinates, and there is no benefit to use the same reference for DEM and Orthophotos. Since orthophotos are mostly available in EPSG:3857, better stick to it too.
