### ISSUE TITLE
Clean unused DDS

### ISSUE THREAD

**Issue by ShiftyFR** [oscarpilote/Ortho4XP#42]
In the last version (1.20b) there was an option to clean unused DDS. Is it possible to do the same with the 1.30 ?

**Comment by d41k4n** [comment]
Sure, simply increase cleaning_level to the desired value (read the help text).

**Comment by ShiftyFR** [comment]
Didn't find the help text :/

**Comment by d41k4n** [comment]
The help text appears as a "hint" pop-up window when pressing on the button "cleaning_level" (or any other parameter for that matter).
