### ISSUE TITLE
Overlay can only be built from Earth View

### ISSUE THREAD

**Issue by hotbso** [oscarpilote/Ortho4XP#44]
When building (or rebuilding) a single tile from the main GUI it's not possible to create the overlay.
No button to select and build_all() does not have a call to OVL.build_overlay() while build_tile_list() has one.

**Comment by oscarpilote** [comment]
Overlay and tiles are two completely independent things. The program only offers the possibility to cut/paste overlays from third party and won't put them in the tile directory but in a unique common directory (which you can use even with no tiles). If you use overlays, I'd suggest to build them "all" at once from the Earth window with just "extract overlays"  checked.
