### ISSUE TITLE
Geoportail Server

### ISSUE THREAD

**Issue by ShiftyFR** [oscarpilote/Ortho4XP#47]
Hi ! Is it possible to add the Geoportail server into Ortho4XP ? It looks like satellite imagery from Geoportail is the best for France :)

**Comment by d41k4n** [comment]
It has been in 1.30 for quote a while:

https://github.com/oscarpilote/Ortho4XP/search?utf8=%E2%9C%93&q=geoportail

The "geoportail" layer is provided by ign.fr.
