### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by gkkes** [oscarpilote/Ortho4XP#48]
My HUGE collection of Ortho4XP tiles are now housed on a new 5Tb drive. Is there any way I can update the map view to see the tiles already done? This would be great to discover which tiles I need to create to complete my collection.
This would be a great feature.
Thanks for your great contribution. O4XP is fab
Kev

**Comment by d41k4n** [comment]
Make sure your Base Folder points to where your ortho scenery is stored/linked (usually X-Plane's "Custom Scenery" folder) and that your scenery folders either use the default naming scheme (zOrtho4XP_*).

If you've left "Base Folder" empty make sure your ortho scenery folders are stored/linked in ./Tiles .

You may also want to check out these links:

https://forums.x-plane.org/index.php?/forums/topic/161768-tiles-missing-form-tiles-collection-and-mgmt-page/&do=findComment&comment=1520219
https://forums.x-plane.org/index.php?/forums/topic/128760-guide-how-to-link-to-tiles-on-another-drive-and-show-them-in-the-global-map

**Comment by CyberGuerro** [comment]
@d41k4n : what you suggest doesen't work for me, in details:
I'm on linux platform and in **Tiles** folder I fisically stored my **zOrto4XP_*** sceneries; in Tiles folder I also create a folder named **_Italy** and into that I created a symlink to **original Tiles/zOrto4XP_* folder**.
When I set **_Italy** as base folder, map shows nothing, instead if I point to **default Tiles folder**, map shows me all tiles made. It seems that Orto4XP doesn't follow symlink in Tiles folder.
