### ISSUE TITLE
v130 Fails to run in Ubuntu 18.04

### ISSUE THREAD

**Issue by chrisbjohannsen** [oscarpilote/Ortho4XP#53]
When launching the script via `python Ortho4XP_130.py` the following error is encountered:

> Traceback (most recent call last):
>  File "Ortho4XP_v130.py", line 9, in <module>
>    import O4_Imagery_Utils as IMG
>  File "./src/O4_Imagery_Utils.py", line 597
> SyntaxError: Non-ASCII character '\xc2' in file ./src/O4_Imagery_Utils.py on line 597, but no encoding > declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by d41k4n** [comment]
It seems you are using Python 2.x
Make sure you execute the script using a Python 3.x runtime.

**Comment by chrisbjohannsen** [comment]
That was it, thank you.
