### ISSUE TITLE
Better cache system

### ISSUE THREAD

**Issue by Tchekda** [oscarpilote/Ortho4XP#61]
Hello,
I have noticed that you are currently using some cache for the OSM data, but i was wondering to add a condition : if all the data is from cache, so the program will also cache the mesh in the Tiles folder for the .poly .node .ele .mesh files, so the rendering will be faster?
And i have another question : the zoom level referres to the QMID or the LOD af the downloaded picture?

**Comment by d41k4n** [comment]
Not sure I understand what you're getting at but you can already "accelerate rendering" by simply running only step 4 as long as there is a .mesh file present in the tile folder.

For posing general questions I'd suggest to use the official support forum: https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/ (you might have to explain what you mean by QMID and LOD and perhaps also consider the fact that Ortho4XP was written for X-Plane).
