### ISSUE TITLE
Allow several directories to be a symlink

### ISSUE THREAD

**Issue by dirtyequi** [oscarpilote/Ortho4XP#62]
Hi,

I need to have the tiles and osm data on a different base directory (or even in directories), but these directories are recreated even if a symlink with the same name exists.
Can you please add support for symlinks?

**Comment by d41k4n** [comment]
> directories are recreated even if a symlink with the same name exists
Can't reproduce this on Windows 10 using folder junctions.

**Comment by dirtyequi** [comment]
Ah, my bad. 
I did not create a symlink but a link which has a different suffix (.lnk). Unfortunately windows does not allow you to create real (directory) symlink from a GUI (or I did not find it), but "mklink.exe /D" worked as intended.
Thanks for pointing me into that direction =)
