### ISSUE TITLE
Problem with the pictures from different providers

### ISSUE THREAD

**Issue by Tchekda** [oscarpilote/Ortho4XP#63]
Hi, i recently noticed that the pictures from Google have strange disposition as you can see on the picture attached to the issue. 

![10832_16816_GO215](https://user-images.githubusercontent.com/23559888/54241112-78d4e900-4520-11e9-924e-9534f7a9691a.jpg)

This appends in ZL15 in each tile but not in each picture. So as you can see the final render is not that good...
![image](https://user-images.githubusercontent.com/23559888/54241732-462bf000-4522-11e9-88c8-448b6658c73d.png)
 So i don't know if this is ony for Google or for other? I prefer Google for the summer picture and green forests....

**Comment by d41k4n** [comment]
That's "normal". You will get discontinuities with practically every provider (the higher the ZL and coverage the higher the risk IMO).

Might also be just temporary as the provider is updating its imagery.

**Comment by Tchekda** [comment]
> That's "normal". You will get discontinuities with practically every provider (the higher the ZL and coverage the higher the risk IMO).
> 
> Might also be just temporary as the provider is updating its imagery.

So you say it's normal? Because in screenshots of other users, it's smooth and without these cuts, so is there a solution or i only have to wait until the provider fixes it?

**Comment by d41k4n** [comment]
If other users used the same provider and ZL that likely means they were lucky and downloaded imagery before the provider "screwed" it up by updating it (possibly with more recent but less uniform orthophoto).

**Comment by Tchekda** [comment]
Thank you,  so i will wait a week or two and will try again....

**Comment by Tchekda** [comment]
So while Google is updating his pictures, i tried with the default Bing source. And another strange problem appears : Big cities's suburb's are in High ZL than the Tile and the center of the city is with a strange texture... 
Here an example with the city of Bordeaux, France at Tile 44-001
![Picture download from bing](https://user-images.githubusercontent.com/23559888/54568750-b03c0d80-49d8-11e9-8c32-7c6d935e89a3.jpg)
![Tile supposed to be in ZL15](https://user-images.githubusercontent.com/23559888/54568801-eb3e4100-49d8-11e9-8cbc-95139f4d5772.png)

**Comment by d41k4n** [comment]
That's an issue with Bing imagery and unrelated to Ortho4XP.
