### ISSUE TITLE
Error Building mesh for tile +40+140

### ISSUE THREAD

**Issue by joshoram80** [oscarpilote/Ortho4XP#66]
I get the following error when attempting to make a tile in Japan. This was the only tile that gave me an error out of the whole of Japan. It is part of a central landmass so it should have decent OSM data.

Step 2 : Building mesh for tile +40+140 : 
--------

-> Modifying curv_tol weight map according to runway locations.
-> Modifying curv_tol weight map according to coastline location.
    * Recycling OSM data from ..\OSM_data\+40+140\+40+140\+40+140_coastline.osm.bz2
-> Start of the mesh algorithm Triangle4XP.
   Loading altitudes from DEM file.
   Loading curv_tol geographic weights.
   Computing curvatures from altitudes.
   Constructing Delaunay triangulation by divide-and-conquer method.
   Recovering segments in Delaunay triangulation.
   Internal error in segmentintersection():
   Topological inconsistency after splitting a segment.
   Splitting subsegment (0.978614661357, 0.57065705109) (0.978737929608, 0.570659482065) at (0.978737929608, 0.570659482065).

WARNING: Triangle4XP could not achieve the requested quality (min_angle), most probably due to an uncatched OSM error.
It will be tempted now with no angle constraint (i.e. min_angle=0).
   Loading altitudes from DEM file.
   Loading curv_tol geographic weights.
   Computing curvatures from altitudes.
   Constructing Delaunay triangulation by divide-and-conquer method.
   Recovering segments in Delaunay triangulation.
   Internal error in segmentintersection():
   Topological inconsistency after splitting a segment.
   Splitting subsegment (0.978614661357, 0.57065705109) (0.978737929608, 0.570659482065) at (0.978737929608, 0.570659482065).

ERROR: Triangle4XP really couldn't make it !

[zOrtho4XP_+40+140.zip](https://github.com/oscarpilote/Ortho4XP/files/3006779/zOrtho4XP_%2B40%2B140.zip)

**Comment by d41k4n** [comment]
This seems to be the problematic spot in OSM:
https://www.openstreetmap.org/query?lat=40.570659482065&lon=140.978737929608#map=18/40.57066/140.97874

I'm guessing it has something to do with that [road segment](https://www.openstreetmap.org/way/111062923) crossing the riverbank polygons ([here](https://www.openstreetmap.org/way/598721280) and [here](https://www.openstreetmap.org/way/598721281)).

You could try opening "./OSM_data/+40+140/+40+140/+40+140_water.osm.bz2" in JOSM and removing the above riverbank polygons. Then re-save and re-create your tile from step 1.

**Comment by d41k4n** [comment]
Alternatively you could also try reducing "mesh_zl" in the config.

**Comment by joshoram80** [comment]
Rather than delete the polys I just moved a few points as they seemed to be
bigger than they needed to anyway. No issues after that. Thanks for the
help!

**Comment by efalcon** [comment]
> Rather than delete the polys I just moved a few points as they seemed to be bigger than they needed to anyway. No issues after that. Thanks for the help!

Hi mate,
I also got this error. As I am not familiar with editing OSM files, would you please tell me how to do that? Or share the edited file?
Thanks.
