### ISSUE TITLE
restore link prefix & BASE FOLDER with subfolders

### ISSUE THREAD

**Issue by CyberGuerro** [oscarpilote/Ortho4XP#68]
It could be very usefull restoring possibility to specify a prefix (like in 1.20b) for links into custom sceneries, when the are created from world map of tiles.

Another usefull implementation could be implement an option to scan RECURSIVELY into BASE FOLDER because for example I grouped my Italy's tiles into "zOrtho4XP_Italy" and Austria's into "zOrtho4XP_Austria" and I'd like to see all tiles (Italy and Austria) alltogether selecting parent folder.

Thank you

**Comment by oscarpilote** [comment]
I agree. This is the kind of stuff that is not really fun to code though.
