### ISSUE TITLE
Feature Request: Transparent Roads

### ISSUE THREAD

**Issue by NickClark** [oscarpilote/Ortho4XP#70]
I think it would result in a more believable world and may even add a little performance. A precedent has already been set by ORBX TrueEarth, and on a [user plugin](https://forums.x-plane.org/index.php?/files/file/41811-road-and-autogen-textures-for_photoscenery/) on X-Plane.org

**Comment by oscarpilote** [comment]
Ortho4XP does not take care of overlays, in particular of roads. You may be referring to the capability to copy/paste overlays from third party (HD mesh or whatever): it just brings what you copy. Here is [third example](https://www.youtube.com/watch?v=IMa6OpAdfEY) showing there may have been a precedent to the precedent.

**Comment by NickClark** [comment]
Hmm... ya, I'm referring to the "Extract overlays" feature. Is there a way to filter what get's copied? I dont want to lose certain landmarks (powerlines, RRs, etc) Wish I could just filter out roads.

**Comment by d41k4n** [comment]
If you would filter out roads from the overlay there would be no cars, signs, streetlights, bridges and embankments anymore. That's likely not how it's done in True Earth because it's all part of the road network.

**Comment by d41k4n** [comment]
Filtering out roads (including cars, streetlights, bridges, embankments etc.) can be done with "ovl_exclude_net" by providing the type indexes to be excluded - as discussed [here](https://forums.x-plane.org/index.php?/forums/topic/139847-v130-bugs/&do=findComment&comment=1353710). By providing the right indexes you can leave in powerlines and railroads for example (look at the default roads.net to determine the indexes).
