### ISSUE TITLE
Saturation adjustment

### ISSUE THREAD

**Issue by stooone** [oscarpilote/Ortho4XP#72]
Hi,

It would be nice to have a setting to do saturation adjustment during the conversion step on all images. I think a float where 1.0 is keep and values greater than 1.0 will increase the saturation of the image and values less than 1.0 will decrease the saturation of the image.

Regards,
Stone

**Comment by d41k4n** [comment]
IMO this is already possible in the context of each provider by using filters.
See https://forums.x-plane.org/index.php?/forums/topic/140834-add-contrast-to-orthophotos/&do=findComment&comment=1490222

**Comment by stooone** [comment]
Wow sounds, great! Thanks!
