### ISSUE TITLE
New filter for Italy and Spain

### ISSUE THREAD

**Issue by CyberGuerro** [oscarpilote/Ortho4XP#73]
attached zip file within filter settings to get (in my opinion) better textures from PCN06 provider's orthophotos (PCN06.flt) and Spain provider (SP/SP2015 - SP_2015.flt).
[Filters.zip](https://github.com/oscarpilote/Ortho4XP/files/3213335/Filters.zip)

**Comment by d41k4n** [comment]
Thanks. You should submit a pull request.

**Comment by CyberGuerro** [comment]
Do it, I hope to do it right :-)
