### ISSUE TITLE
Latest 1.3 branch doesn't build texture data

### ISSUE THREAD

**Issue by feanor91** [oscarpilote/Ortho4XP#78]
Hello

I've downloaded the latest branch Ortho4XP-feature-smart_airport_zl a few hours ago, Because OSM provider was broken, so, osm data works, but netherless what I try, I'm not able to have the dds txture files. I check I run python in 64 bit and have 16Go of ram (foun a post where the problem seems to be related to 32 bits version and memory) I check to imprint_masks_to_dds is set to false (found in the same post, I think), so, don't know what to do next.

**Comment by d41k4n** [comment]
If you get the same issue using the master branch I suggest doing a search in the support forum as this has been discussed many times, along with possible solutions.

https://forums.x-plane.org/index.php?/forums/forum/322-ortho4xp/

If it's exclusive to this branch I suggest posting in https://forums.x-plane.org/index.php?/forums/topic/147570-feature-automated-zoom-levels-around-airports/ instead.

**Comment by feanor91** [comment]
Hi thanks, it solves the problems
First, I found in thread 147570 a patch to fix osm data not loading, and second 1.30 master works just fine at downloading orthophotos so bug is in the branch not in the master (exept the osm provider stuff, of course)

**Comment by d41k4n** [comment]
The broken OSM provider should be fixed with https://github.com/oscarpilote/Ortho4XP/pull/77
