### ISSUE TITLE
Street network not generated when extracting overlays from default scenery

### ISSUE THREAD

**Issue by coolh** [oscarpilote/Ortho4XP#8]
Hi Oscar,

I am doing some beta testing of your great software, and the road extraction seems to fail when creating overlays. I attached the log and a screenshot of the result. I am from Argentina, in south America, the location is SAZM airport, but the result is the same in other places.

Thanks for your time and dedication.

[log.txt](https://github.com/oscarpilote/Ortho4XP/files/1693235/log.txt)
![screenshoot](https://user-images.githubusercontent.com/18689369/35781552-4ff6cfcc-09ca-11e8-9b86-10e79dd1db4e.png)

**Comment by coolh** [comment]
Hi,
Looking at the X-Plane Log, I found DSF errors on the generated tile (-38,-58):

WARNING: scenery file for -38,-58 has no vertices in its right edge.  This usually indicates a bad DSF file.
WARNING: scenery file for -38,-58 has no vertices in its top edge.  This usually indicates a bad DSF file.
0:00:37.145 I/FLT: Init dat_p0 type:loc_ram apt:SAZM start at:4
0:00:37.468 I/SCN: DSF load time: 1145185 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-39-058.dsf (30439 tris)
0:00:37.468 I/SCN: DSF load time: 1256265 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-37-058.dsf (64224 tris)
0:00:37.468 I/SCN: DSF load time: 1305941 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-39-060.dsf (65100 tris)
0:00:37.468 I/SCN: DSF load time: 1452639 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-37-060.dsf (89263 tris)
0:00:37.468 I/DSF: Warning for missing scenery file: -39-057
0:00:37.468 I/SCN: DSF load time: 504811 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-37-057.dsf (28076 tris)
0:00:37.468 I/SCN: DSF load time: 748299 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-39-059.dsf (61031 tris)
0:00:37.468 I/SCN: DSF load time: 793492 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-37-059.dsf (79204 tris)
0:00:37.468 I/SCN: DSF load time: 335939 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-38-057.dsf (9208 tris)
0:00:37.468 I/SCN: DSF load time: 175452 for file Custom Scenery/SAZM/Earth nav data/-40-060/-38-058.dsf (0 tris)
0:00:37.468 I/SCN: DSF load time: 105563 for file Custom Scenery/Global Airports/Earth nav data/-40-060/-38-058.dsf (0 tris)
0:00:37.468 I/SCN: DSF load time: 215482 for file D:\Ortho4xp-Trunk\yOrtho4XP_Overlays/Earth nav data/-40-060/-38-058.dsf (0 tris)
0:00:37.468 I/SCN: DSF load time: 284942 for file Custom Scenery/zOrtho4XP_-38-058/Earth nav data/-40-060/-38-058.dsf (81083 tris)
0:00:37.468 I/SCN: DSF load time: 1359897 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-38-060.dsf (135535 tris)
0:00:37.468 I/SCN: DSF load time: 894076 for file Global Scenery/X-Plane 11 Global Scenery/Earth nav data/-40-060/-38-059.dsf (119916 tris)
0:00:47.414 D/STM: Transitioning from state state_NormalLoading to state_Normal

**Comment by d41k4n** [comment]
Unable to reproduce this with the latest master.
