### ISSUE TITLE
Demo areas have to have their overlays built seperately

### ISSUE THREAD

**Issue by Valkyrien04** [oscarpilote/Ortho4XP#84]
The demo Scenery areas (KSEA and LOWI) have their overlay data exist in <xp_root>\Global Scenery\X Plane 11 Demo Areas\ vs the usual Global Scenery\X Plane 11 Global Scenery\

You can't target both folders simultaneously so you have to build the overlays twice.

**Comment by d41k4n** [comment]
You can easily work around this by either moving folder Global Scenery\X Plane 11 Demo Areas\Earth nav data to Global Scenery\X Plane 11 Global Scenery\ or creating symlinks for the "Demo" DSF's at the appropriate locations under Global Scenery\X Plane 11 Global Scenery\Earth nav data\...

**Comment by ashmanmedia** [comment]
For all I made this screenshot of the actual demo areas tile wise.
![DEMO AREAS](https://user-images.githubusercontent.com/3086735/72226701-ef3be080-3561-11ea-82d0-d9a8daefd633.jpg)
