### ISSUE TITLE
Build Geotiff doesn't work

### ISSUE THREAD

**Issue by stackTom** [oscarpilote/Ortho4XP#85]
Building geotiffs throws a FileNotFoundError after downloading the appropriate jpg file. This is on windows 10 64 bit.

**Comment by d41k4n** [comment]
Confirm you have installed GDAL package and adjusted the PATH variable as described in the [install_instructions.txt](https://github.com/oscarpilote/Ortho4XP/blob/master/Install_Instructions.txt#L49)?

**Comment by stackTom** [comment]
That fixed it, thanks!
