### ISSUE TITLE
[FR] OSM url is deprecated

### ISSUE THREAD

**Issue by hargn** [oscarpilote/Ortho4XP#86]
After an issue with the overpass server of the french OSM mirror, the team of openstreetmap.fr indicated to me that the URL used by Ortho4XP is deprecated.

So the url of overpass_server for FR should be changed from "http://api.openstreetmap.fr/oapi/interpreter" to "http://overpass.openstreetmap.fr/oapi/interpreter".

**Comment by oscarpilote** [comment]
Thank you, can you make a PR for that one ?

**Comment by hargn** [comment]
Done in #87
