### ISSUE TITLE
Installing in macOS Mojave

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#91]
I followed the instructions for Mac and got all sorts of activity, downloads etc as seen in the terminal.
However, when I ran the .py script, I got the following:
Ortho4XP-master trav$ python3 Ortho4XP_v130.py 
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 14, in <module>
    import O4_Geo_Utils as GEO
  File "./src/O4_Geo_Utils.py", line 2, in <module>
    import pyproj
**ModuleNotFoundError: No module named 'pyproj'**

**Comment by d41k4n** [comment]
You did not install the module pyproj.

What happens after you execute the following on the command line:

`pip3 install git+https://github.com/jswhit/pyproj.git`

?

Also, maybe have a look [here](https://forums.x-plane.org/index.php?/forums/topic/129672-ortho4xp-mac-install-for-dummies-guide-with-pics-updated-v130/) for advice.

**Comment by OldSubSailor** [comment]
Thank you for your reply, however, that step was not listed in the OS X install instructions page, and I do not know if it was supposed to be.
OS X
----

1) In a Terminal window, install Homebrew (brew.sh), a package manager
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

2) Go to the Ortho4XP folder
cd /path/to/Ortho4XP

3) Execute the install script (you may have to run "chmod +x ./install_mac.sh" first)
./install_mac.sh

4) Launch Ortho4XP
python3 Ortho4XP_v130.py


========================================================================================
TravsiMac:~ trav$ pip3 install git+https://github.com/jswhit/pyproj.git
Collecting git+https://github.com/jswhit/pyproj.git
  Cloning https://github.com/jswhit/pyproj.git to /private/var/folders/yp/cqmgk6md6qsd57n2t0n1n_kw0000gn/T/pip-req-build-a7w0ombx
  Running command git clone -q https://github.com/jswhit/pyproj.git /private/var/folders/yp/cqmgk6md6qsd57n2t0n1n_kw0000gn/T/pip-req-build-a7w0ombx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied (use --upgrade to upgrade): pyproj==2.2.2 from git+https://github.com/jswhit/pyproj.git in /usr/local/lib/python3.7/site-packages
Building wheels for collected packages: pyproj
  Building wheel for pyproj (PEP 517) ... done
  Stored in directory: /private/var/folders/yp/cqmgk6md6qsd57n2t0n1n_kw0000gn/T/pip-ephem-wheel-cache-fwv16plr/wheels/21/68/3d/f6f41eabec9e7f3e6170a08455cc13a8555ec77eb85eb39f2b
Successfully built pyproj

THEN I GET THIS

TravsiMac:Ortho4XP-master trav$ python3 Ortho4XP_v130.py
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 14, in <module>
    import O4_Geo_Utils as GEO
  File "./src/O4_Geo_Utils.py", line 2, in <module>
    import pyproj
ModuleNotFoundError: No module named 'pyproj'
========================================================================================

I then looked for it, and it seems to be there:

TravsiMac:~ trav$ locate pyproj
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/__pycache__/pyproject.cpython-36.pyc
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/pyproject.py
/usr/local/Cellar/python/3.7.4/libexec/pip/build/lib/pip/_internal/pyproject.py
/usr/local/Cellar/python/3.7.4/libexec/pip/pyproject.toml
/usr/local/Cellar/python/3.7.4/libexec/pip/src/pip/_internal/pyproject.py
/usr/local/Cellar/python@2/2.7.16/libexec/pip/build/lib/pip/_internal/pyproject.py
/usr/local/Cellar/python@2/2.7.16/libexec/pip/pyproject.toml
/usr/local/Cellar/python@2/2.7.16/libexec/pip/src/pip/_internal/pyproject.py
/usr/local/lib/python2.7/site-packages/pip/_internal/pyproject.py
/usr/local/lib/python2.7/site-packages/pip/_internal/pyproject.pyc
/usr/local/lib/python3.7/site-packages/pip/_internal/__pycache__/pyproject.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pip/_internal/pyproject.py
/usr/local/lib/python3.7/site-packages/pyproj
/usr/local/lib/python3.7/site-packages/pyproj/__init__.py
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/__init__.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/_show_versions.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/cf1x8.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/compat.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/crs.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/datadir.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/enums.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/exceptions.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/geod.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/proj.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/transformer.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/__pycache__/utils.cpython-37.pyc
/usr/local/lib/python3.7/site-packages/pyproj/_crs.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/pyproj/_datadir.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/pyproj/_geod.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/pyproj/_list.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/pyproj/_proj.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/pyproj/_show_versions.py
/usr/local/lib/python3.7/site-packages/pyproj/_transformer.cpython-37m-darwin.so
/usr/local/lib/python3.7/site-packages/pyproj/cf1x8.py
/usr/local/lib/python3.7/site-packages/pyproj/compat.py
/usr/local/lib/python3.7/site-packages/pyproj/crs.py
/usr/local/lib/python3.7/site-packages/pyproj/datadir.py
/usr/local/lib/python3.7/site-packages/pyproj/enums.py
/usr/local/lib/python3.7/site-packages/pyproj/exceptions.py
/usr/local/lib/python3.7/site-packages/pyproj/geod.py
/usr/local/lib/python3.7/site-packages/pyproj/proj.py
/usr/local/lib/python3.7/site-packages/pyproj/transformer.py
/usr/local/lib/python3.7/site-packages/pyproj/utils.py
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/INSTALLER
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/LICENSE
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/LICENSE_proj4
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/METADATA
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/RECORD
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/WHEEL
/usr/local/lib/python3.7/site-packages/pyproj-2.2.2.dist-info/top_level.txt

**Comment by OldSubSailor** [comment]
I think that the shell script is not functioning properly; however; the link that you provided : https://forums.x-plane.org/index.php?/forums/topic/129672-ortho4xp-mac-install-for-dummies-guide-with-pics-updated-v130/
Does. The shell script is not used,  and each package of software is downloaded and installed separately. This seems to eliminate the errors that I see.

Also, I may not be reading the installation process correctly as it goes streaming by in Mac Terminal, but it sure looks like python is getting installed, or perhaps it is a reference to python access; it looks like python2. 

I sure wish that there was a manual for the program.  I found one online, but it is apparently far out of date. 

thank you
