### ISSUE TITLE
Ortho4xp

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#96]
Ortho4xp was working fine until I installed the new macOS upgrade; macOS 10.15 (Catalina).
There appear some new security things that I can't get past once the program starts running.
It appears to get killed when the triangles.app utility starts up for example. 
<img width="434" alt="Screen Shot 2019-10-09 at 1 56 58 PM" src="https://user-images.githubusercontent.com/54075170/66513273-57c97c00-eaa0-11e9-9b02-51f752e4a28e.png">

**Comment by OldSubSailor** [comment]
<img width="425" alt="Screen Shot 2019-10-09 at 1 59 56 PM" src="https://user-images.githubusercontent.com/54075170/66513330-7a5b9500-eaa0-11e9-8597-74a0fd58908a.png">

**Comment by rvt** [comment]
you might be looking for the spctl tool

**Comment by OldSubSailor** [comment]
Thank you for your reply, however, when I try to open that link, I just get a blank page.

**Comment by OldSubSailor** [comment]
This is a new Apple security kind of thing, and requires a system preferences interaction.
