### ISSUE TITLE
Python 3.8 Issue

### ISSUE THREAD

**Issue by OldSubSailor** [oscarpilote/Ortho4XP#98]
It seems that I have all sorts of Python versions on my imac now.  The macOS 2.7 and 3.7.3 and the 3.7.4 that was installed when I first setup ortho4.

Things were working fine until I  installed Python 3.8. It looks like the python3 call accesses the newest version of Python (I have to call python3.7 in the command line for it to come up)
In this case it (3.8) does not work.
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

So the apparent fix at this time for Python 3.8  is to use:
python3.7 Ortho4XP_v130.py
in your call.

**Comment by namarrgon** [comment]
I don't know how you manage your python environments but you need to install https://pypi.org/project/requests/ for python 3.8 as well.

**Comment by OldSubSailor** [comment]
Thank you

I just have python on an iMac and have one system, and version 3.7 & 3.8. I don’t really understand what you are telling me.

**Comment by OldSubSailor** [comment]
So my question remains, why doesn't ortho work with python 3.8?

**Comment by d41k4n** [comment]
Ortho4XP works great with Python 3.8. Your issue is with a missing Python module "requests". Looks like you didn't follow the install instructions.

**Comment by OldSubSailor** [comment]
Howdy,

I think that I did follow the instructions for Mac as per the below link, and it was working for python 3.7.x. 

https://forums.x-plane.org/index.php?/forums/topic/129672-ortho4xp-mac-install-for-dummies-guide-with-pics-updated-v130/& <https://forums.x-plane.org/index.php?/forums/topic/129672-ortho4xp-mac-install-for-dummies-guide-with-pics-updated-v130/&>


There appear to be some missing steps in the install script for Mac, so I had to use the steps outlined above. 

Python3 calls up python 3.8, so I had to call ortho with a python3.7 command, after reinstalling python 3.7.

Perhaps something was missed in the steps outlined above?

Thank you
Trav

**Comment by OldSubSailor** [comment]
Also,
I am now running macOS Catalina which is a bag of worms, and it also defaults to the zsh, which I do not know makes a difference.

**Comment by OldSubSailor** [comment]
Alas, still bothering you,

If you could review that X Plane forums link that I sent earlier to see if anything is missing or needs to be improved I would appreciate it. 

Trav

**Comment by OldSubSailor** [comment]
I finally saw the install instructions here. They look like a condensed version of what is on the x plane forum. So far things are working on Python 3.8. However I think that the new Catalina security and Zsh may be causing issues.

**Comment by OldSubSailor** [comment]
Actually I did, seeing as how I ran the unix install shell script. 

A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P
