### ISSUE TITLE
Triangle4XP Catalina 

### ISSUE THREAD

**Issue by Boomernerd46** [oscarpilote/Ortho4XP#99]
I've enjoyed the detail scenery created and 'relative' ease of using your program. I've built four large areas without incident. In attempting to build another recently I ran into a rejection of Triangle4XP by the MacOS 15.10.2 that only had Cancel as useful option as mentioned in some previous posts at least on the X-plane org forums. I can't determine if it is the security issue with MacOS gatekeeper, my machine, or something else. 

I'm hoping this is the site for such issues. I've attached the text file of the results of my recent attempt, the .poly and .node files, and my iMac hardware description 

as requested. 

thank you
boomernerd46@gmail.com
[Triangle4XP to GitHub.TXT](https://github.com/oscarpilote/Ortho4XP/files/3970195/Triangle4XP.to.GitHub.TXT)
[Imac hardware description.TXT](https://github.com/oscarpilote/Ortho4XP/files/3970204/Imac.hardware.description.TXT)
[Data+45-070.node.zip](https://github.com/oscarpilote/Ortho4XP/files/3970207/Data%2B45-070.node.zip)
[Data+45-070.poly.zip](https://github.com/oscarpilote/Ortho4XP/files/3970208/Data%2B45-070.poly.zip)

**Comment by d41k4n** [comment]
https://forums.x-plane.org/index.php?/forums/topic/192403-issues-with-macos-1015-catalina/
